/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class chilkat {
  public static byte[] SWIG_JavaArrayOutUchar(SWIGTYPE_p_JNIEnv jenv, SWIGTYPE_p_unsigned_char data, long sz) {
    return chilkatJNI.SWIG_JavaArrayOutUchar(SWIGTYPE_p_JNIEnv.getCPtr(jenv), SWIGTYPE_p_unsigned_char.getCPtr(data), sz);
  }

  public static void SWIG_JavaArrayInUchar(SWIGTYPE_p_JNIEnv jenv, CkByteData arg1, byte[] arr) {
    chilkatJNI.SWIG_JavaArrayInUchar(SWIGTYPE_p_JNIEnv.getCPtr(jenv), CkByteData.getCPtr(arg1), arg1, arr);
  }

}
