/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkCertStore {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkCertStore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkCertStore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkCertStore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkCertStore() {
    this(chilkatJNI.new_CkCertStore(), true);
  }

  public CkCert FindCertByRfc822Name(String name) {
    long cPtr = chilkatJNI.CkCertStore_FindCertByRfc822Name(swigCPtr, this, name);
    return (cPtr == 0) ? null : new CkCert(cPtr, false);
  }

  public CkCert FindCertBySha1Thumbprint(String str) {
    long cPtr = chilkatJNI.CkCertStore_FindCertBySha1Thumbprint(swigCPtr, this, str);
    return (cPtr == 0) ? null : new CkCert(cPtr, false);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkCertStore_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkCertStore_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean get_AvoidWindowsPkAccess() {
    return chilkatJNI.CkCertStore_get_AvoidWindowsPkAccess(swigCPtr, this);
  }

  public void put_AvoidWindowsPkAccess(boolean newVal) {
    chilkatJNI.CkCertStore_put_AvoidWindowsPkAccess(swigCPtr, this, newVal);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkCertStore_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkCertStore_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkCertStore_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public String lastErrorText() {
    return chilkatJNI.CkCertStore_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkCertStore_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkCertStore_lastErrorHtml(swigCPtr, this);
  }

  public String version() {
    return chilkatJNI.CkCertStore_version(swigCPtr, this);
  }

  public boolean LoadPfxFile(String filename, String password) {
    return chilkatJNI.CkCertStore_LoadPfxFile(swigCPtr, this, filename, password);
  }

  public boolean LoadPfxData(CkByteData pfxData, String password) {
    return chilkatJNI.CkCertStore_LoadPfxData(swigCPtr, this, CkByteData.getCPtr(pfxData), pfxData, password);
  }

  public boolean LoadPfxData2(SWIGTYPE_p_unsigned_char buf, int bufLen, String password) {
    return chilkatJNI.CkCertStore_LoadPfxData2(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(buf), bufLen, password);
  }

  public CkCert FindCertBySerial(String serialNumber) {
    long cPtr = chilkatJNI.CkCertStore_FindCertBySerial(swigCPtr, this, serialNumber);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert FindCertBySubjectE(String emailAddress) {
    long cPtr = chilkatJNI.CkCertStore_FindCertBySubjectE(swigCPtr, this, emailAddress);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert FindCertBySubjectO(String organization) {
    long cPtr = chilkatJNI.CkCertStore_FindCertBySubjectO(swigCPtr, this, organization);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert FindCertBySubjectCN(String commonName) {
    long cPtr = chilkatJNI.CkCertStore_FindCertBySubjectCN(swigCPtr, this, commonName);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert FindCertBySubject(String subject) {
    long cPtr = chilkatJNI.CkCertStore_FindCertBySubject(swigCPtr, this, subject);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert GetCertificate(int index) {
    long cPtr = chilkatJNI.CkCertStore_GetCertificate(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public int get_NumCertificates() {
    return chilkatJNI.CkCertStore_get_NumCertificates(swigCPtr, this);
  }

  public void get_Version(CkString version) {
    chilkatJNI.CkCertStore_get_Version(swigCPtr, this, CkString.getCPtr(version), version);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkCertStore_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkCertStore_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkCertStore_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkCertStore_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

}
