/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkCompression {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkCompression(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkCompression obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkCompression(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkCompression() {
    this(chilkatJNI.new_CkCompression(), true);
  }

  public void get_Charset(CkString str) {
    chilkatJNI.CkCompression_get_Charset(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String charset() {
    return chilkatJNI.CkCompression_charset(swigCPtr, this);
  }

  public void put_Charset(String newVal) {
    chilkatJNI.CkCompression_put_Charset(swigCPtr, this, newVal);
  }

  public void get_EncodingMode(CkString str) {
    chilkatJNI.CkCompression_get_EncodingMode(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String encodingMode() {
    return chilkatJNI.CkCompression_encodingMode(swigCPtr, this);
  }

  public void put_EncodingMode(String newVal) {
    chilkatJNI.CkCompression_put_EncodingMode(swigCPtr, this, newVal);
  }

  public boolean UnlockComponent(String unlockCode) {
    return chilkatJNI.CkCompression_UnlockComponent(swigCPtr, this, unlockCode);
  }

  public void get_Algorithm(CkString str) {
    chilkatJNI.CkCompression_get_Algorithm(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String algorithm() {
    return chilkatJNI.CkCompression_algorithm(swigCPtr, this);
  }

  public void put_Algorithm(String newVal) {
    chilkatJNI.CkCompression_put_Algorithm(swigCPtr, this, newVal);
  }

  public boolean BeginCompressBytes(CkByteData data, CkByteData outBytes) {
    return chilkatJNI.CkCompression_BeginCompressBytes(swigCPtr, this, CkByteData.getCPtr(data), data, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean BeginCompressBytesENC(CkByteData data, CkString outStr) {
    return chilkatJNI.CkCompression_BeginCompressBytesENC(swigCPtr, this, CkByteData.getCPtr(data), data, CkString.getCPtr(outStr), outStr);
  }

  public String beginCompressBytesENC(CkByteData data) {
    return chilkatJNI.CkCompression_beginCompressBytesENC(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean BeginCompressString(String str, CkByteData outBytes) {
    return chilkatJNI.CkCompression_BeginCompressString(swigCPtr, this, str, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean BeginCompressStringENC(String str, CkString outStr) {
    return chilkatJNI.CkCompression_BeginCompressStringENC(swigCPtr, this, str, CkString.getCPtr(outStr), outStr);
  }

  public String beginCompressStringENC(String str) {
    return chilkatJNI.CkCompression_beginCompressStringENC(swigCPtr, this, str);
  }

  public boolean BeginDecompressBytes(CkByteData data, CkByteData outBytes) {
    return chilkatJNI.CkCompression_BeginDecompressBytes(swigCPtr, this, CkByteData.getCPtr(data), data, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean BeginDecompressBytesENC(String str, CkByteData outBytes) {
    return chilkatJNI.CkCompression_BeginDecompressBytesENC(swigCPtr, this, str, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean BeginDecompressString(CkByteData data, CkString outStr) {
    return chilkatJNI.CkCompression_BeginDecompressString(swigCPtr, this, CkByteData.getCPtr(data), data, CkString.getCPtr(outStr), outStr);
  }

  public String beginDecompressString(CkByteData data) {
    return chilkatJNI.CkCompression_beginDecompressString(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean BeginDecompressStringENC(String str, CkString outStr) {
    return chilkatJNI.CkCompression_BeginDecompressStringENC(swigCPtr, this, str, CkString.getCPtr(outStr), outStr);
  }

  public String beginDecompressStringENC(String str) {
    return chilkatJNI.CkCompression_beginDecompressStringENC(swigCPtr, this, str);
  }

  public boolean CompressBytes(CkByteData data, CkByteData outBytes) {
    return chilkatJNI.CkCompression_CompressBytes(swigCPtr, this, CkByteData.getCPtr(data), data, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean CompressBytesENC(CkByteData data, CkString outStr) {
    return chilkatJNI.CkCompression_CompressBytesENC(swigCPtr, this, CkByteData.getCPtr(data), data, CkString.getCPtr(outStr), outStr);
  }

  public String compressBytesENC(CkByteData data) {
    return chilkatJNI.CkCompression_compressBytesENC(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean CompressFile(String inFile, String outFile) {
    return chilkatJNI.CkCompression_CompressFile(swigCPtr, this, inFile, outFile);
  }

  public boolean CompressString(String str, CkByteData outBytes) {
    return chilkatJNI.CkCompression_CompressString(swigCPtr, this, str, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean CompressStringENC(String str, CkString outStr) {
    return chilkatJNI.CkCompression_CompressStringENC(swigCPtr, this, str, CkString.getCPtr(outStr), outStr);
  }

  public String compressStringENC(String str) {
    return chilkatJNI.CkCompression_compressStringENC(swigCPtr, this, str);
  }

  public boolean DecompressBytes(CkByteData data, CkByteData outBytes) {
    return chilkatJNI.CkCompression_DecompressBytes(swigCPtr, this, CkByteData.getCPtr(data), data, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean DecompressBytesENC(String str, CkByteData outBytes) {
    return chilkatJNI.CkCompression_DecompressBytesENC(swigCPtr, this, str, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean DecompressFile(String inFile, String outFile) {
    return chilkatJNI.CkCompression_DecompressFile(swigCPtr, this, inFile, outFile);
  }

  public boolean DecompressString(CkByteData data, CkString outStr) {
    return chilkatJNI.CkCompression_DecompressString(swigCPtr, this, CkByteData.getCPtr(data), data, CkString.getCPtr(outStr), outStr);
  }

  public String decompressString(CkByteData data) {
    return chilkatJNI.CkCompression_decompressString(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean DecompressStringENC(String str, CkString outStr) {
    return chilkatJNI.CkCompression_DecompressStringENC(swigCPtr, this, str, CkString.getCPtr(outStr), outStr);
  }

  public String decompressStringENC(String str) {
    return chilkatJNI.CkCompression_decompressStringENC(swigCPtr, this, str);
  }

  public boolean EndCompressBytes(CkByteData outBytes) {
    return chilkatJNI.CkCompression_EndCompressBytes(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean EndCompressBytesENC(CkString outStr) {
    return chilkatJNI.CkCompression_EndCompressBytesENC(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String endCompressBytesENC() {
    return chilkatJNI.CkCompression_endCompressBytesENC(swigCPtr, this);
  }

  public boolean EndCompressString(CkByteData outBytes) {
    return chilkatJNI.CkCompression_EndCompressString(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean EndCompressStringENC(CkString outStr) {
    return chilkatJNI.CkCompression_EndCompressStringENC(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String endCompressStringENC() {
    return chilkatJNI.CkCompression_endCompressStringENC(swigCPtr, this);
  }

  public boolean EndDecompressBytes(CkByteData outBytes) {
    return chilkatJNI.CkCompression_EndDecompressBytes(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean EndDecompressBytesENC(CkByteData outBytes) {
    return chilkatJNI.CkCompression_EndDecompressBytesENC(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean EndDecompressString(CkString outStr) {
    return chilkatJNI.CkCompression_EndDecompressString(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String endDecompressString() {
    return chilkatJNI.CkCompression_endDecompressString(swigCPtr, this);
  }

  public boolean EndDecompressStringENC(CkString outStr) {
    return chilkatJNI.CkCompression_EndDecompressStringENC(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String endDecompressStringENC() {
    return chilkatJNI.CkCompression_endDecompressStringENC(swigCPtr, this);
  }

  public boolean MoreCompressBytes(CkByteData data, CkByteData outBytes) {
    return chilkatJNI.CkCompression_MoreCompressBytes(swigCPtr, this, CkByteData.getCPtr(data), data, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean MoreCompressBytesENC(CkByteData data, CkString outStr) {
    return chilkatJNI.CkCompression_MoreCompressBytesENC(swigCPtr, this, CkByteData.getCPtr(data), data, CkString.getCPtr(outStr), outStr);
  }

  public String moreCompressBytesENC(CkByteData data) {
    return chilkatJNI.CkCompression_moreCompressBytesENC(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean MoreCompressString(String str, CkByteData outBytes) {
    return chilkatJNI.CkCompression_MoreCompressString(swigCPtr, this, str, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean MoreCompressStringENC(String str, CkString outStr) {
    return chilkatJNI.CkCompression_MoreCompressStringENC(swigCPtr, this, str, CkString.getCPtr(outStr), outStr);
  }

  public String moreCompressStringENC(String str) {
    return chilkatJNI.CkCompression_moreCompressStringENC(swigCPtr, this, str);
  }

  public boolean MoreDecompressBytes(CkByteData data, CkByteData outBytes) {
    return chilkatJNI.CkCompression_MoreDecompressBytes(swigCPtr, this, CkByteData.getCPtr(data), data, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean MoreDecompressBytesENC(String str, CkByteData outBytes) {
    return chilkatJNI.CkCompression_MoreDecompressBytesENC(swigCPtr, this, str, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean MoreDecompressString(CkByteData data, CkString outStr) {
    return chilkatJNI.CkCompression_MoreDecompressString(swigCPtr, this, CkByteData.getCPtr(data), data, CkString.getCPtr(outStr), outStr);
  }

  public String moreDecompressString(CkByteData data) {
    return chilkatJNI.CkCompression_moreDecompressString(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean MoreDecompressStringENC(String str, CkString outStr) {
    return chilkatJNI.CkCompression_MoreDecompressStringENC(swigCPtr, this, str, CkString.getCPtr(outStr), outStr);
  }

  public String moreDecompressStringENC(String str) {
    return chilkatJNI.CkCompression_moreDecompressStringENC(swigCPtr, this, str);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkCompression_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkCompression_version(swigCPtr, this);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkCompression_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkCompression_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkCompression_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkCompression_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkCompression_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkCompression_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkCompression_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkCompression_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkCompression_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkCompression_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkCompression_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkCompression_lastErrorHtml(swigCPtr, this);
  }

}
