/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkEmail {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkEmail(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkEmail obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkEmail(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkEmail() {
    this(chilkatJNI.new_CkEmail(), true);
  }

  public String lastErrorText() {
    return chilkatJNI.CkEmail_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkEmail_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkEmail_lastErrorHtml(swigCPtr, this);
  }

  public boolean AddDataAttachment2(String fileName, CkByteData content, String contentType) {
    return chilkatJNI.CkEmail_AddDataAttachment2(swigCPtr, this, fileName, CkByteData.getCPtr(content), content, contentType);
  }

  public void AppendToBody(String str) {
    chilkatJNI.CkEmail_AppendToBody(swigCPtr, this, str);
  }

  public boolean GetAltHeaderField(int index, String fieldName, CkString outStr) {
    return chilkatJNI.CkEmail_GetAltHeaderField(swigCPtr, this, index, fieldName, CkString.getCPtr(outStr), outStr);
  }

  public String getAltHeaderField(int index, String fieldName) {
    return chilkatJNI.CkEmail_getAltHeaderField(swigCPtr, this, index, fieldName);
  }

  public boolean GetDeliveryStatusInfo(String fieldName, CkString outStr) {
    return chilkatJNI.CkEmail_GetDeliveryStatusInfo(swigCPtr, this, fieldName, CkString.getCPtr(outStr), outStr);
  }

  public String getDeliveryStatusInfo(String fieldName) {
    return chilkatJNI.CkEmail_getDeliveryStatusInfo(swigCPtr, this, fieldName);
  }

  public boolean GetAttachedMessageFilename(int index, CkString outStr) {
    return chilkatJNI.CkEmail_GetAttachedMessageFilename(swigCPtr, this, index, CkString.getCPtr(outStr), outStr);
  }

  public String getAttachedMessageFilename(int index) {
    return chilkatJNI.CkEmail_getAttachedMessageFilename(swigCPtr, this, index);
  }

  public boolean LoadXmlString(String xmlStr) {
    return chilkatJNI.CkEmail_LoadXmlString(swigCPtr, this, xmlStr);
  }

  public boolean SetAttachmentCharset(int index, String charset) {
    return chilkatJNI.CkEmail_SetAttachmentCharset(swigCPtr, this, index, charset);
  }

  public boolean SetFromMimeObject(CkMime mime) {
    return chilkatJNI.CkEmail_SetFromMimeObject(swigCPtr, this, CkMime.getCPtr(mime), mime);
  }

  public boolean AspUnpack(String prefix, String saveDir, String urlPath, boolean cleanFiles) {
    return chilkatJNI.CkEmail_AspUnpack(swigCPtr, this, prefix, saveDir, urlPath, cleanFiles);
  }

  public boolean AspUnpack2(String prefix, String saveDir, String urlPath, boolean cleanFiles, CkByteData outBytes) {
    return chilkatJNI.CkEmail_AspUnpack2(swigCPtr, this, prefix, saveDir, urlPath, cleanFiles, CkByteData.getCPtr(outBytes), outBytes);
  }

  public int GetImapUid() {
    return chilkatJNI.CkEmail_GetImapUid(swigCPtr, this);
  }

  public boolean HasHeaderMatching(String fieldName, String valuePattern, boolean caseInsensitive) {
    return chilkatJNI.CkEmail_HasHeaderMatching(swigCPtr, this, fieldName, valuePattern, caseInsensitive);
  }

  public void get_Language(CkString str) {
    chilkatJNI.CkEmail_get_Language(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String language() {
    return chilkatJNI.CkEmail_language(swigCPtr, this);
  }

  public CkStringArray GetDsnFinalRecipients() {
    long cPtr = chilkatJNI.CkEmail_GetDsnFinalRecipients(swigCPtr, this);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, false);
  }

  public boolean GetRelatedContentLocation(int index, CkString outStr) {
    return chilkatJNI.CkEmail_GetRelatedContentLocation(swigCPtr, this, index, CkString.getCPtr(outStr), outStr);
  }

  public String getRelatedContentLocation(int index) {
    return chilkatJNI.CkEmail_getRelatedContentLocation(swigCPtr, this, index);
  }

  public void GetMimeBinary(CkByteData outBytes) {
    chilkatJNI.CkEmail_GetMimeBinary(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean AttachMessage(CkByteData mimeBytes) {
    return chilkatJNI.CkEmail_AttachMessage(swigCPtr, this, CkByteData.getCPtr(mimeBytes), mimeBytes);
  }

  public boolean ComputeGlobalKey(String encoding, boolean bFold, CkString outStr) {
    return chilkatJNI.CkEmail_ComputeGlobalKey(swigCPtr, this, encoding, bFold, CkString.getCPtr(outStr), outStr);
  }

  public String computeGlobalKey(String encoding, boolean bFold) {
    return chilkatJNI.CkEmail_computeGlobalKey(swigCPtr, this, encoding, bFold);
  }

  public int get_NumDaysOld() {
    return chilkatJNI.CkEmail_get_NumDaysOld(swigCPtr, this);
  }

  public void get_PreferredCharset(CkString str) {
    chilkatJNI.CkEmail_get_PreferredCharset(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String preferredCharset() {
    return chilkatJNI.CkEmail_preferredCharset(swigCPtr, this);
  }

  public void put_PreferredCharset(String newVal) {
    chilkatJNI.CkEmail_put_PreferredCharset(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkEmail_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkEmail_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public void AddRelatedHeader(int index, String fieldName, String fieldValue) {
    chilkatJNI.CkEmail_AddRelatedHeader(swigCPtr, this, index, fieldName, fieldValue);
  }

  public void ClearEncryptCerts() {
    chilkatJNI.CkEmail_ClearEncryptCerts(swigCPtr, this);
  }

  public boolean AddEncryptCert(CkCert cert) {
    return chilkatJNI.CkEmail_AddEncryptCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean UnpackHtml(String unpackDir, String htmlFilename, String partsSubdir) {
    return chilkatJNI.CkEmail_UnpackHtml(swigCPtr, this, unpackDir, htmlFilename, partsSubdir);
  }

  public boolean SetFromMimeBytes(CkByteData mimeBytes) {
    return chilkatJNI.CkEmail_SetFromMimeBytes(swigCPtr, this, CkByteData.getCPtr(mimeBytes), mimeBytes);
  }

  public boolean SetAttachmentDisposition(int index, String disposition) {
    return chilkatJNI.CkEmail_SetAttachmentDisposition(swigCPtr, this, index, disposition);
  }

  public void RemoveHtmlAlternative() {
    chilkatJNI.CkEmail_RemoveHtmlAlternative(swigCPtr, this);
  }

  public void RemovePlainTextAlternative() {
    chilkatJNI.CkEmail_RemovePlainTextAlternative(swigCPtr, this);
  }

  public void AddHeaderField2(String fieldName, String fieldValue) {
    chilkatJNI.CkEmail_AddHeaderField2(swigCPtr, this, fieldName, fieldValue);
  }

  public boolean get_PrependHeaders() {
    return chilkatJNI.CkEmail_get_PrependHeaders(swigCPtr, this);
  }

  public void put_PrependHeaders(boolean newVal) {
    chilkatJNI.CkEmail_put_PrependHeaders(swigCPtr, this, newVal);
  }

  public CkEmail CreateDsn(String explanation, String xmlDeliveryStatus, boolean bHeaderOnly) {
    long cPtr = chilkatJNI.CkEmail_CreateDsn(swigCPtr, this, explanation, xmlDeliveryStatus, bHeaderOnly);
    return (cPtr == 0) ? null : new CkEmail(cPtr, false);
  }

  public CkEmail CreateMdn(String explanation, String xmlMdnFields, boolean bHeaderOnly) {
    long cPtr = chilkatJNI.CkEmail_CreateMdn(swigCPtr, this, explanation, xmlMdnFields, bHeaderOnly);
    return (cPtr == 0) ? null : new CkEmail(cPtr, false);
  }

  public void get_SigningHashAlg(CkString str) {
    chilkatJNI.CkEmail_get_SigningHashAlg(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String signingHashAlg() {
    return chilkatJNI.CkEmail_signingHashAlg(swigCPtr, this);
  }

  public void put_SigningHashAlg(String newVal) {
    chilkatJNI.CkEmail_put_SigningHashAlg(swigCPtr, this, newVal);
  }

  public void get_Pkcs7CryptAlg(CkString str) {
    chilkatJNI.CkEmail_get_Pkcs7CryptAlg(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String pkcs7CryptAlg() {
    return chilkatJNI.CkEmail_pkcs7CryptAlg(swigCPtr, this);
  }

  public void put_Pkcs7CryptAlg(String newVal) {
    chilkatJNI.CkEmail_put_Pkcs7CryptAlg(swigCPtr, this, newVal);
  }

  public int get_Pkcs7KeyLength() {
    return chilkatJNI.CkEmail_get_Pkcs7KeyLength(swigCPtr, this);
  }

  public void put_Pkcs7KeyLength(int newVal) {
    chilkatJNI.CkEmail_put_Pkcs7KeyLength(swigCPtr, this, newVal);
  }

  public int get_NumReports() {
    return chilkatJNI.CkEmail_get_NumReports(swigCPtr, this);
  }

  public boolean GetReport(int index, CkString outStr) {
    return chilkatJNI.CkEmail_GetReport(swigCPtr, this, index, CkString.getCPtr(outStr), outStr);
  }

  public String getReport(int index) {
    return chilkatJNI.CkEmail_getReport(swigCPtr, this, index);
  }

  public boolean GetAlternativeBodyByContentType(String contentType, CkString outStr) {
    return chilkatJNI.CkEmail_GetAlternativeBodyByContentType(swigCPtr, this, contentType, CkString.getCPtr(outStr), outStr);
  }

  public String getAlternativeBodyByContentType(String contentType) {
    return chilkatJNI.CkEmail_getAlternativeBodyByContentType(swigCPtr, this, contentType);
  }

  public boolean AddPfxSourceData(CkByteData pfxData, String password) {
    return chilkatJNI.CkEmail_AddPfxSourceData(swigCPtr, this, CkByteData.getCPtr(pfxData), pfxData, password);
  }

  public boolean AddPfxSourceFile(String pfxFilePath, String password) {
    return chilkatJNI.CkEmail_AddPfxSourceFile(swigCPtr, this, pfxFilePath, password);
  }

  public boolean get_UnpackUseRelPaths() {
    return chilkatJNI.CkEmail_get_UnpackUseRelPaths(swigCPtr, this);
  }

  public void put_UnpackUseRelPaths(boolean newVal) {
    chilkatJNI.CkEmail_put_UnpackUseRelPaths(swigCPtr, this, newVal);
  }

  public boolean AddiCalendarAlternativeBody(String body, String methodName) {
    return chilkatJNI.CkEmail_AddiCalendarAlternativeBody(swigCPtr, this, body, methodName);
  }

  public boolean AddRelatedData(String fileName, CkByteData inData, CkString outStr) {
    return chilkatJNI.CkEmail_AddRelatedData(swigCPtr, this, fileName, CkByteData.getCPtr(inData), inData, CkString.getCPtr(outStr), outStr);
  }

  public String addRelatedData(String fileName, CkByteData inData) {
    return chilkatJNI.CkEmail_addRelatedData(swigCPtr, this, fileName, CkByteData.getCPtr(inData), inData);
  }

  public void AddRelatedData2(CkByteData inData, String fileNameInHtml) {
    chilkatJNI.CkEmail_AddRelatedData2(swigCPtr, this, CkByteData.getCPtr(inData), inData, fileNameInHtml);
  }

  public boolean SetFromMimeBytes2(CkByteData mimeBytes, String charset) {
    return chilkatJNI.CkEmail_SetFromMimeBytes2(swigCPtr, this, CkByteData.getCPtr(mimeBytes), mimeBytes, charset);
  }

  public CkDateTime GetDt() {
    long cPtr = chilkatJNI.CkEmail_GetDt(swigCPtr, this);
    return (cPtr == 0) ? null : new CkDateTime(cPtr, false);
  }

  public boolean SetDt(CkDateTime dt) {
    return chilkatJNI.CkEmail_SetDt(swigCPtr, this, CkDateTime.getCPtr(dt), dt);
  }

  public CkCert FindIssuer(CkCert cert) {
    long cPtr = chilkatJNI.CkEmail_FindIssuer(swigCPtr, this, CkCert.getCPtr(cert), cert);
    return (cPtr == 0) ? null : new CkCert(cPtr, false);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkEmail_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkEmail_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkEmail_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public void get_EmailDateStr(CkString str) {
    chilkatJNI.CkEmail_get_EmailDateStr(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String emailDateStr() {
    return chilkatJNI.CkEmail_emailDateStr(swigCPtr, this);
  }

  public void put_EmailDateStr(String newVal) {
    chilkatJNI.CkEmail_put_EmailDateStr(swigCPtr, this, newVal);
  }

  public void get_LocalDateStr(CkString str) {
    chilkatJNI.CkEmail_get_LocalDateStr(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String localDateStr() {
    return chilkatJNI.CkEmail_localDateStr(swigCPtr, this);
  }

  public void put_LocalDateStr(String newVal) {
    chilkatJNI.CkEmail_put_LocalDateStr(swigCPtr, this, newVal);
  }

  public boolean SetRelatedFilename(int index, String filename) {
    return chilkatJNI.CkEmail_SetRelatedFilename(swigCPtr, this, index, filename);
  }

  public void SetTextBody(String bodyText, String contentType) {
    chilkatJNI.CkEmail_SetTextBody(swigCPtr, this, bodyText, contentType);
  }

  public String getRelatedStringCrLf(int index, String charset) {
    return chilkatJNI.CkEmail_getRelatedStringCrLf(swigCPtr, this, index, charset);
  }

  public String getRelatedContentID(int index) {
    return chilkatJNI.CkEmail_getRelatedContentID(swigCPtr, this, index);
  }

  public String getRelatedFilename(int index) {
    return chilkatJNI.CkEmail_getRelatedFilename(swigCPtr, this, index);
  }

  public String getRelatedString(int index, String charset) {
    return chilkatJNI.CkEmail_getRelatedString(swigCPtr, this, index, charset);
  }

  public String getAlternativeBody(int index) {
    return chilkatJNI.CkEmail_getAlternativeBody(swigCPtr, this, index);
  }

  public String getAlternativeContentType(int index) {
    return chilkatJNI.CkEmail_getAlternativeContentType(swigCPtr, this, index);
  }

  public String getHtmlBody() {
    return chilkatJNI.CkEmail_getHtmlBody(swigCPtr, this);
  }

  public String getPlainTextBody() {
    return chilkatJNI.CkEmail_getPlainTextBody(swigCPtr, this);
  }

  public String getHeaderFieldName(int index) {
    return chilkatJNI.CkEmail_getHeaderFieldName(swigCPtr, this, index);
  }

  public String getHeaderFieldValue(int index) {
    return chilkatJNI.CkEmail_getHeaderFieldValue(swigCPtr, this, index);
  }

  public String getAttachmentStringCrLf(int index, String charset) {
    return chilkatJNI.CkEmail_getAttachmentStringCrLf(swigCPtr, this, index, charset);
  }

  public String getAttachmentContentID(int index) {
    return chilkatJNI.CkEmail_getAttachmentContentID(swigCPtr, this, index);
  }

  public String getAttachmentContentType(int index) {
    return chilkatJNI.CkEmail_getAttachmentContentType(swigCPtr, this, index);
  }

  public String getAttachmentHeader(int index, String fieldName) {
    return chilkatJNI.CkEmail_getAttachmentHeader(swigCPtr, this, index, fieldName);
  }

  public String getAttachmentString(int index, String charset) {
    return chilkatJNI.CkEmail_getAttachmentString(swigCPtr, this, index, charset);
  }

  public String getAttachmentFilename(int index) {
    return chilkatJNI.CkEmail_getAttachmentFilename(swigCPtr, this, index);
  }

  public String getHeaderField(String fieldName) {
    return chilkatJNI.CkEmail_getHeaderField(swigCPtr, this, fieldName);
  }

  public String getBcc(int index) {
    return chilkatJNI.CkEmail_getBcc(swigCPtr, this, index);
  }

  public String getCC(int index) {
    return chilkatJNI.CkEmail_getCC(swigCPtr, this, index);
  }

  public String getTo(int index) {
    return chilkatJNI.CkEmail_getTo(swigCPtr, this, index);
  }

  public String getBccAddr(int index) {
    return chilkatJNI.CkEmail_getBccAddr(swigCPtr, this, index);
  }

  public String getCcAddr(int index) {
    return chilkatJNI.CkEmail_getCcAddr(swigCPtr, this, index);
  }

  public String getToAddr(int index) {
    return chilkatJNI.CkEmail_getToAddr(swigCPtr, this, index);
  }

  public String getBccName(int index) {
    return chilkatJNI.CkEmail_getBccName(swigCPtr, this, index);
  }

  public String getCcName(int index) {
    return chilkatJNI.CkEmail_getCcName(swigCPtr, this, index);
  }

  public String getToName(int index) {
    return chilkatJNI.CkEmail_getToName(swigCPtr, this, index);
  }

  public String getMime() {
    return chilkatJNI.CkEmail_getMime(swigCPtr, this);
  }

  public String getXml() {
    return chilkatJNI.CkEmail_getXml(swigCPtr, this);
  }

  public String uidl() {
    return chilkatJNI.CkEmail_uidl(swigCPtr, this);
  }

  public String charset() {
    return chilkatJNI.CkEmail_charset(swigCPtr, this);
  }

  public String encryptedBy() {
    return chilkatJNI.CkEmail_encryptedBy(swigCPtr, this);
  }

  public String signedBy() {
    return chilkatJNI.CkEmail_signedBy(swigCPtr, this);
  }

  public String fromAddress() {
    return chilkatJNI.CkEmail_fromAddress(swigCPtr, this);
  }

  public String fromName() {
    return chilkatJNI.CkEmail_fromName(swigCPtr, this);
  }

  public String mailer() {
    return chilkatJNI.CkEmail_mailer(swigCPtr, this);
  }

  public String header() {
    return chilkatJNI.CkEmail_header(swigCPtr, this);
  }

  public String ck_from() {
    return chilkatJNI.CkEmail_ck_from(swigCPtr, this);
  }

  public String subject() {
    return chilkatJNI.CkEmail_subject(swigCPtr, this);
  }

  public String replyTo() {
    return chilkatJNI.CkEmail_replyTo(swigCPtr, this);
  }

  public String bounceAddress() {
    return chilkatJNI.CkEmail_bounceAddress(swigCPtr, this);
  }

  public String body() {
    return chilkatJNI.CkEmail_body(swigCPtr, this);
  }

  public String qEncodeString(String str, String charset) {
    return chilkatJNI.CkEmail_qEncodeString(swigCPtr, this, str, charset);
  }

  public String bEncodeString(String str, String charset) {
    return chilkatJNI.CkEmail_bEncodeString(swigCPtr, this, str, charset);
  }

  public String addFileAttachment(String fileName) {
    return chilkatJNI.CkEmail_addFileAttachment(swigCPtr, this, fileName);
  }

  public String addRelatedFile(String fileName) {
    return chilkatJNI.CkEmail_addRelatedFile(swigCPtr, this, fileName);
  }

  public String addRelatedString(String nameInHtml, String str, String charset) {
    return chilkatJNI.CkEmail_addRelatedString(swigCPtr, this, nameInHtml, str, charset);
  }

  public String getReplaceString2(String pattern) {
    return chilkatJNI.CkEmail_getReplaceString2(swigCPtr, this, pattern);
  }

  public String getReplaceString(int index) {
    return chilkatJNI.CkEmail_getReplaceString(swigCPtr, this, index);
  }

  public String getReplacePattern(int index) {
    return chilkatJNI.CkEmail_getReplacePattern(swigCPtr, this, index);
  }

  public String generateFilename() {
    return chilkatJNI.CkEmail_generateFilename(swigCPtr, this);
  }

  public String fileDistList() {
    return chilkatJNI.CkEmail_fileDistList(swigCPtr, this);
  }

  public String createTempMht(String inFilename) {
    return chilkatJNI.CkEmail_createTempMht(swigCPtr, this, inFilename);
  }

  public boolean GetRelatedContentType(int index, CkString strContentType) {
    return chilkatJNI.CkEmail_GetRelatedContentType(swigCPtr, this, index, CkString.getCPtr(strContentType), strContentType);
  }

  public String getRelatedContentType(int index) {
    return chilkatJNI.CkEmail_getRelatedContentType(swigCPtr, this, index);
  }

  public void AddRelatedString2(String str, String charset, String filenameInHtml) {
    chilkatJNI.CkEmail_AddRelatedString2(swigCPtr, this, str, charset, filenameInHtml);
  }

  public boolean AddRelatedFile2(String filenameOnDisk, String filenameInHtml) {
    return chilkatJNI.CkEmail_AddRelatedFile2(swigCPtr, this, filenameOnDisk, filenameInHtml);
  }

  public boolean AddStringAttachment(String fileName, String str) {
    return chilkatJNI.CkEmail_AddStringAttachment(swigCPtr, this, fileName, str);
  }

  public boolean AddStringAttachment2(String fileName, String str, String charset) {
    return chilkatJNI.CkEmail_AddStringAttachment2(swigCPtr, this, fileName, str, charset);
  }

  public boolean AddRelatedString(String filenameInHtml, String str, String charset, CkString cid) {
    return chilkatJNI.CkEmail_AddRelatedString(swigCPtr, this, filenameInHtml, str, charset, CkString.getCPtr(cid), cid);
  }

  public boolean SetFromMimeText(String mimeText) {
    return chilkatJNI.CkEmail_SetFromMimeText(swigCPtr, this, mimeText);
  }

  public boolean SetFromMimeText2(String mimeText, int numBytes) {
    return chilkatJNI.CkEmail_SetFromMimeText2(swigCPtr, this, mimeText, numBytes);
  }

  public boolean LoadEml(String mimeFilename) {
    return chilkatJNI.CkEmail_LoadEml(swigCPtr, this, mimeFilename);
  }

  public boolean LoadXml(String xmlFilename) {
    return chilkatJNI.CkEmail_LoadXml(swigCPtr, this, xmlFilename);
  }

  public boolean SetFromXmlText(String xmlStr) {
    return chilkatJNI.CkEmail_SetFromXmlText(swigCPtr, this, xmlStr);
  }

  public boolean ZipAttachments(String zipFilename) {
    return chilkatJNI.CkEmail_ZipAttachments(swigCPtr, this, zipFilename);
  }

  public boolean UnzipAttachments() {
    return chilkatJNI.CkEmail_UnzipAttachments(swigCPtr, this);
  }

  public boolean AesEncrypt(String password) {
    return chilkatJNI.CkEmail_AesEncrypt(swigCPtr, this, password);
  }

  public boolean AesDecrypt(String password) {
    return chilkatJNI.CkEmail_AesDecrypt(swigCPtr, this, password);
  }

  public CkEmail Clone() {
    long cPtr = chilkatJNI.CkEmail_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkEmail CreateForward() {
    long cPtr = chilkatJNI.CkEmail_CreateForward(swigCPtr, this);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkEmail CreateReply() {
    long cPtr = chilkatJNI.CkEmail_CreateReply(swigCPtr, this);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkCert GetSignedByCert() {
    long cPtr = chilkatJNI.CkEmail_GetSignedByCert(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert GetEncryptedByCert() {
    long cPtr = chilkatJNI.CkEmail_GetEncryptedByCert(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert GetEncryptCert() {
    long cPtr = chilkatJNI.CkEmail_GetEncryptCert(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert GetSigningCert() {
    long cPtr = chilkatJNI.CkEmail_GetSigningCert(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public boolean SetEncryptCert(CkCert cert) {
    return chilkatJNI.CkEmail_SetEncryptCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean SetSigningCert(CkCert cert) {
    return chilkatJNI.CkEmail_SetSigningCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean SetSigningCert2(CkCert cert, CkPrivateKey key) {
    return chilkatJNI.CkEmail_SetSigningCert2(swigCPtr, this, CkCert.getCPtr(cert), cert, CkPrivateKey.getCPtr(key), key);
  }

  public boolean GetFileContent(String filename, CkByteData bData) {
    return chilkatJNI.CkEmail_GetFileContent(swigCPtr, this, filename, CkByteData.getCPtr(bData), bData);
  }

  public boolean GetRelatedStringCrLf(int index, String charset, CkString str) {
    return chilkatJNI.CkEmail_GetRelatedStringCrLf(swigCPtr, this, index, charset, CkString.getCPtr(str), str);
  }

  public boolean GetRelatedContentID(int index, CkString strContentID) {
    return chilkatJNI.CkEmail_GetRelatedContentID(swigCPtr, this, index, CkString.getCPtr(strContentID), strContentID);
  }

  public boolean GetRelatedFilename(int index, CkString strFilename) {
    return chilkatJNI.CkEmail_GetRelatedFilename(swigCPtr, this, index, CkString.getCPtr(strFilename), strFilename);
  }

  public boolean GetRelatedString(int index, String charset, CkString strData) {
    return chilkatJNI.CkEmail_GetRelatedString(swigCPtr, this, index, charset, CkString.getCPtr(strData), strData);
  }

  public boolean GetRelatedData(int index, CkByteData buffer) {
    return chilkatJNI.CkEmail_GetRelatedData(swigCPtr, this, index, CkByteData.getCPtr(buffer), buffer);
  }

  public void AddHeaderField(String fieldName, String fieldValue) {
    chilkatJNI.CkEmail_AddHeaderField(swigCPtr, this, fieldName, fieldValue);
  }

  public void RemoveHeaderField(String fieldName) {
    chilkatJNI.CkEmail_RemoveHeaderField(swigCPtr, this, fieldName);
  }

  public void SetHtmlBody(String html) {
    chilkatJNI.CkEmail_SetHtmlBody(swigCPtr, this, html);
  }

  public boolean SaveRelatedItem(int index, String directory) {
    return chilkatJNI.CkEmail_SaveRelatedItem(swigCPtr, this, index, directory);
  }

  public void DropRelatedItem(int index) {
    chilkatJNI.CkEmail_DropRelatedItem(swigCPtr, this, index);
  }

  public void DropRelatedItems() {
    chilkatJNI.CkEmail_DropRelatedItems(swigCPtr, this);
  }

  public boolean AddRelatedFile(String fileName, CkString strContentID) {
    return chilkatJNI.CkEmail_AddRelatedFile(swigCPtr, this, fileName, CkString.getCPtr(strContentID), strContentID);
  }

  public boolean AddHtmlAlternativeBody(String body) {
    return chilkatJNI.CkEmail_AddHtmlAlternativeBody(swigCPtr, this, body);
  }

  public boolean AddPlainTextAlternativeBody(String body) {
    return chilkatJNI.CkEmail_AddPlainTextAlternativeBody(swigCPtr, this, body);
  }

  public boolean GetAlternativeBody(int index, CkString strBody) {
    return chilkatJNI.CkEmail_GetAlternativeBody(swigCPtr, this, index, CkString.getCPtr(strBody), strBody);
  }

  public boolean GetAlternativeContentType(int index, CkString strContentType) {
    return chilkatJNI.CkEmail_GetAlternativeContentType(swigCPtr, this, index, CkString.getCPtr(strContentType), strContentType);
  }

  public boolean GetHtmlBody(CkString strBody) {
    return chilkatJNI.CkEmail_GetHtmlBody(swigCPtr, this, CkString.getCPtr(strBody), strBody);
  }

  public boolean GetPlainTextBody(CkString strBody) {
    return chilkatJNI.CkEmail_GetPlainTextBody(swigCPtr, this, CkString.getCPtr(strBody), strBody);
  }

  public int get_NumHeaderFields() {
    return chilkatJNI.CkEmail_get_NumHeaderFields(swigCPtr, this);
  }

  public boolean GetHeaderFieldName(int index, CkString strFieldName) {
    return chilkatJNI.CkEmail_GetHeaderFieldName(swigCPtr, this, index, CkString.getCPtr(strFieldName), strFieldName);
  }

  public boolean GetHeaderFieldValue(int index, CkString strFieldValue) {
    return chilkatJNI.CkEmail_GetHeaderFieldValue(swigCPtr, this, index, CkString.getCPtr(strFieldValue), strFieldValue);
  }

  public boolean GetAttachmentStringCrLf(int index, String charset, CkString strData) {
    return chilkatJNI.CkEmail_GetAttachmentStringCrLf(swigCPtr, this, index, charset, CkString.getCPtr(strData), strData);
  }

  public boolean GetAttachmentContentID(int index, CkString strContentID) {
    return chilkatJNI.CkEmail_GetAttachmentContentID(swigCPtr, this, index, CkString.getCPtr(strContentID), strContentID);
  }

  public boolean GetAttachmentContentType(int index, CkString strContentType) {
    return chilkatJNI.CkEmail_GetAttachmentContentType(swigCPtr, this, index, CkString.getCPtr(strContentType), strContentType);
  }

  public boolean GetAttachmentHeader(int index, String fieldName, CkString fieldValue) {
    return chilkatJNI.CkEmail_GetAttachmentHeader(swigCPtr, this, index, fieldName, CkString.getCPtr(fieldValue), fieldValue);
  }

  public int GetAttachmentSize(int index) {
    return chilkatJNI.CkEmail_GetAttachmentSize(swigCPtr, this, index);
  }

  public boolean GetAttachmentString(int index, String charset, CkString str) {
    return chilkatJNI.CkEmail_GetAttachmentString(swigCPtr, this, index, charset, CkString.getCPtr(str), str);
  }

  public boolean SaveAllAttachments(String directory) {
    return chilkatJNI.CkEmail_SaveAllAttachments(swigCPtr, this, directory);
  }

  public boolean SaveAttachedFile(int index, String directory) {
    return chilkatJNI.CkEmail_SaveAttachedFile(swigCPtr, this, index, directory);
  }

  public boolean GetAttachmentData(int index, CkByteData buffer) {
    return chilkatJNI.CkEmail_GetAttachmentData(swigCPtr, this, index, CkByteData.getCPtr(buffer), buffer);
  }

  public boolean DropSingleAttachment(int index) {
    return chilkatJNI.CkEmail_DropSingleAttachment(swigCPtr, this, index);
  }

  public boolean SetAttachmentFilename(int index, String filename) {
    return chilkatJNI.CkEmail_SetAttachmentFilename(swigCPtr, this, index, filename);
  }

  public boolean GetAttachmentFilename(int index, CkString strFilename) {
    return chilkatJNI.CkEmail_GetAttachmentFilename(swigCPtr, this, index, CkString.getCPtr(strFilename), strFilename);
  }

  public void AddAttachmentHeader(int index, String fieldName, String fieldValue) {
    chilkatJNI.CkEmail_AddAttachmentHeader(swigCPtr, this, index, fieldName, fieldValue);
  }

  public void DropAttachments() {
    chilkatJNI.CkEmail_DropAttachments(swigCPtr, this);
  }

  public boolean AddFileAttachment(String fileName, CkString strContentType) {
    return chilkatJNI.CkEmail_AddFileAttachment(swigCPtr, this, fileName, CkString.getCPtr(strContentType), strContentType);
  }

  public boolean AddFileAttachment2(String fileName, String contentType) {
    return chilkatJNI.CkEmail_AddFileAttachment2(swigCPtr, this, fileName, contentType);
  }

  public int get_NumReplacePatterns() {
    return chilkatJNI.CkEmail_get_NumReplacePatterns(swigCPtr, this);
  }

  public boolean GetReplaceString2(String pattern, CkString str) {
    return chilkatJNI.CkEmail_GetReplaceString2(swigCPtr, this, pattern, CkString.getCPtr(str), str);
  }

  public boolean GetReplaceString(int index, CkString str) {
    return chilkatJNI.CkEmail_GetReplaceString(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetReplacePattern(int index, CkString strPattern) {
    return chilkatJNI.CkEmail_GetReplacePattern(swigCPtr, this, index, CkString.getCPtr(strPattern), strPattern);
  }

  public boolean SetReplacePattern(String pattern, String replaceString) {
    return chilkatJNI.CkEmail_SetReplacePattern(swigCPtr, this, pattern, replaceString);
  }

  public void GenerateFilename(CkString strFilename) {
    chilkatJNI.CkEmail_GenerateFilename(swigCPtr, this, CkString.getCPtr(strFilename), strFilename);
  }

  public boolean AddMultipleBcc(String commaSeparatedAddresses) {
    return chilkatJNI.CkEmail_AddMultipleBcc(swigCPtr, this, commaSeparatedAddresses);
  }

  public boolean AddMultipleCC(String commaSeparatedAddresses) {
    return chilkatJNI.CkEmail_AddMultipleCC(swigCPtr, this, commaSeparatedAddresses);
  }

  public boolean AddMultipleTo(String commaSeparatedAddresses) {
    return chilkatJNI.CkEmail_AddMultipleTo(swigCPtr, this, commaSeparatedAddresses);
  }

  public boolean GetHeaderField(String fieldName, CkString strFieldData) {
    return chilkatJNI.CkEmail_GetHeaderField(swigCPtr, this, fieldName, CkString.getCPtr(strFieldData), strFieldData);
  }

  public boolean GetBcc(int index, CkString str) {
    return chilkatJNI.CkEmail_GetBcc(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetCC(int index, CkString str) {
    return chilkatJNI.CkEmail_GetCC(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetTo(int index, CkString str) {
    return chilkatJNI.CkEmail_GetTo(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetBccAddr(int index, CkString str) {
    return chilkatJNI.CkEmail_GetBccAddr(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetCcAddr(int index, CkString str) {
    return chilkatJNI.CkEmail_GetCcAddr(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetToAddr(int index, CkString str) {
    return chilkatJNI.CkEmail_GetToAddr(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetBccName(int index, CkString str) {
    return chilkatJNI.CkEmail_GetBccName(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetCcName(int index, CkString str) {
    return chilkatJNI.CkEmail_GetCcName(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetToName(int index, CkString str) {
    return chilkatJNI.CkEmail_GetToName(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public void ClearBcc() {
    chilkatJNI.CkEmail_ClearBcc(swigCPtr, this);
  }

  public void ClearCC() {
    chilkatJNI.CkEmail_ClearCC(swigCPtr, this);
  }

  public void ClearTo() {
    chilkatJNI.CkEmail_ClearTo(swigCPtr, this);
  }

  public boolean AddBcc(String friendlyName, String emailAddress) {
    return chilkatJNI.CkEmail_AddBcc(swigCPtr, this, friendlyName, emailAddress);
  }

  public boolean AddCC(String friendlyName, String emailAddress) {
    return chilkatJNI.CkEmail_AddCC(swigCPtr, this, friendlyName, emailAddress);
  }

  public boolean AddTo(String friendlyName, String emailAddress) {
    return chilkatJNI.CkEmail_AddTo(swigCPtr, this, friendlyName, emailAddress);
  }

  public void GetMime(CkString strMime) {
    chilkatJNI.CkEmail_GetMime(swigCPtr, this, CkString.getCPtr(strMime), strMime);
  }

  public void GetXml(CkString strXml) {
    chilkatJNI.CkEmail_GetXml(swigCPtr, this, CkString.getCPtr(strXml), strXml);
  }

  public boolean SaveXml(String filename) {
    return chilkatJNI.CkEmail_SaveXml(swigCPtr, this, filename);
  }

  public boolean SaveEml(String filename) {
    return chilkatJNI.CkEmail_SaveEml(swigCPtr, this, filename);
  }

  public void get_Uidl(CkString str) {
    chilkatJNI.CkEmail_get_Uidl(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean get_ReturnReceipt() {
    return chilkatJNI.CkEmail_get_ReturnReceipt(swigCPtr, this);
  }

  public void put_ReturnReceipt(boolean newVal) {
    chilkatJNI.CkEmail_put_ReturnReceipt(swigCPtr, this, newVal);
  }

  public int get_Size() {
    return chilkatJNI.CkEmail_get_Size(swigCPtr, this);
  }

  public int get_NumAlternatives() {
    return chilkatJNI.CkEmail_get_NumAlternatives(swigCPtr, this);
  }

  public int get_NumRelatedItems() {
    return chilkatJNI.CkEmail_get_NumRelatedItems(swigCPtr, this);
  }

  public boolean get_SendEncrypted() {
    return chilkatJNI.CkEmail_get_SendEncrypted(swigCPtr, this);
  }

  public void put_SendEncrypted(boolean newVal) {
    chilkatJNI.CkEmail_put_SendEncrypted(swigCPtr, this, newVal);
  }

  public void get_FileDistList(CkString str) {
    chilkatJNI.CkEmail_get_FileDistList(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_FileDistList(String str) {
    chilkatJNI.CkEmail_put_FileDistList(swigCPtr, this, str);
  }

  public void get_Charset(CkString str) {
    chilkatJNI.CkEmail_get_Charset(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Charset(String str) {
    chilkatJNI.CkEmail_put_Charset(swigCPtr, this, str);
  }

  public boolean get_OverwriteExisting() {
    return chilkatJNI.CkEmail_get_OverwriteExisting(swigCPtr, this);
  }

  public void put_OverwriteExisting(boolean newVal) {
    chilkatJNI.CkEmail_put_OverwriteExisting(swigCPtr, this, newVal);
  }

  public boolean get_SendSigned() {
    return chilkatJNI.CkEmail_get_SendSigned(swigCPtr, this);
  }

  public void put_SendSigned(boolean newVal) {
    chilkatJNI.CkEmail_put_SendSigned(swigCPtr, this, newVal);
  }

  public void get_EncryptedBy(CkString str) {
    chilkatJNI.CkEmail_get_EncryptedBy(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean get_Decrypted() {
    return chilkatJNI.CkEmail_get_Decrypted(swigCPtr, this);
  }

  public boolean get_SignaturesValid() {
    return chilkatJNI.CkEmail_get_SignaturesValid(swigCPtr, this);
  }

  public void get_SignedBy(CkString str) {
    chilkatJNI.CkEmail_get_SignedBy(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean get_ReceivedSigned() {
    return chilkatJNI.CkEmail_get_ReceivedSigned(swigCPtr, this);
  }

  public boolean get_ReceivedEncrypted() {
    return chilkatJNI.CkEmail_get_ReceivedEncrypted(swigCPtr, this);
  }

  public int get_NumAttachments() {
    return chilkatJNI.CkEmail_get_NumAttachments(swigCPtr, this);
  }

  public void get_FromAddress(CkString str) {
    chilkatJNI.CkEmail_get_FromAddress(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_FromAddress(String str) {
    chilkatJNI.CkEmail_put_FromAddress(swigCPtr, this, str);
  }

  public void get_FromName(CkString str) {
    chilkatJNI.CkEmail_get_FromName(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_FromName(String str) {
    chilkatJNI.CkEmail_put_FromName(swigCPtr, this, str);
  }

  public void get_LocalDate(SYSTEMTIME sysTime) {
    chilkatJNI.CkEmail_get_LocalDate(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public void get_EmailDate(SYSTEMTIME sysTime) {
    chilkatJNI.CkEmail_get_EmailDate(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public void put_LocalDate(SYSTEMTIME sysTime) {
    chilkatJNI.CkEmail_put_LocalDate(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public void put_EmailDate(SYSTEMTIME sysTime) {
    chilkatJNI.CkEmail_put_EmailDate(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public void get_Mailer(CkString str) {
    chilkatJNI.CkEmail_get_Mailer(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Mailer(String str) {
    chilkatJNI.CkEmail_put_Mailer(swigCPtr, this, str);
  }

  public void get_Header(CkString str) {
    chilkatJNI.CkEmail_get_Header(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public int get_NumBcc() {
    return chilkatJNI.CkEmail_get_NumBcc(swigCPtr, this);
  }

  public int get_NumCC() {
    return chilkatJNI.CkEmail_get_NumCC(swigCPtr, this);
  }

  public int get_NumTo() {
    return chilkatJNI.CkEmail_get_NumTo(swigCPtr, this);
  }

  public void get_From(CkString str) {
    chilkatJNI.CkEmail_get_From(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_From(String str) {
    chilkatJNI.CkEmail_put_From(swigCPtr, this, str);
  }

  public void get_Subject(CkString str) {
    chilkatJNI.CkEmail_get_Subject(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Subject(String str) {
    chilkatJNI.CkEmail_put_Subject(swigCPtr, this, str);
  }

  public void get_ReplyTo(CkString str) {
    chilkatJNI.CkEmail_get_ReplyTo(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_ReplyTo(String str) {
    chilkatJNI.CkEmail_put_ReplyTo(swigCPtr, this, str);
  }

  public void get_BounceAddress(CkString str) {
    chilkatJNI.CkEmail_get_BounceAddress(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_BounceAddress(String str) {
    chilkatJNI.CkEmail_put_BounceAddress(swigCPtr, this, str);
  }

  public void get_Body(CkString str) {
    chilkatJNI.CkEmail_get_Body(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Body(String str) {
    chilkatJNI.CkEmail_put_Body(swigCPtr, this, str);
  }

  public boolean UidlEquals(CkEmail e) {
    return chilkatJNI.CkEmail_UidlEquals(swigCPtr, this, CkEmail.getCPtr(e), e);
  }

  public boolean CreateTempMht(String inFilename, CkString tempMhtFilename) {
    return chilkatJNI.CkEmail_CreateTempMht(swigCPtr, this, inFilename, CkString.getCPtr(tempMhtFilename), tempMhtFilename);
  }

  public CkMime GetMimeObject() {
    long cPtr = chilkatJNI.CkEmail_GetMimeObject(swigCPtr, this);
    return (cPtr == 0) ? null : new CkMime(cPtr, true);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkEmail_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkEmail_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkEmail_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkEmail_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean GetMbPlainTextBody(String charset, CkByteData data) {
    return chilkatJNI.CkEmail_GetMbPlainTextBody(swigCPtr, this, charset, CkByteData.getCPtr(data), data);
  }

  public boolean GetMbHtmlBody(String charset, CkByteData data) {
    return chilkatJNI.CkEmail_GetMbHtmlBody(swigCPtr, this, charset, CkByteData.getCPtr(data), data);
  }

  public boolean GetMbHeaderField(String fieldName, CkByteData fieldData) {
    return chilkatJNI.CkEmail_GetMbHeaderField(swigCPtr, this, fieldName, CkByteData.getCPtr(fieldData), fieldData);
  }

  public boolean GetMbHeaderField2(String charset, String fieldName, CkByteData fieldData) {
    return chilkatJNI.CkEmail_GetMbHeaderField2(swigCPtr, this, charset, fieldName, CkByteData.getCPtr(fieldData), fieldData);
  }

  public boolean QEncodeString(String str, String charset, CkString encodedStr) {
    return chilkatJNI.CkEmail_QEncodeString(swigCPtr, this, str, charset, CkString.getCPtr(encodedStr), encodedStr);
  }

  public boolean BEncodeString(String str, String charset, CkString encodedStr) {
    return chilkatJNI.CkEmail_BEncodeString(swigCPtr, this, str, charset, CkString.getCPtr(encodedStr), encodedStr);
  }

  public int get_NumAttachedMessages() {
    return chilkatJNI.CkEmail_get_NumAttachedMessages(swigCPtr, this);
  }

  public CkEmail GetAttachedMessage(int index) {
    long cPtr = chilkatJNI.CkEmail_GetAttachedMessage(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public void RemoveAttachedMessages() {
    chilkatJNI.CkEmail_RemoveAttachedMessages(swigCPtr, this);
  }

  public void RemoveAttachedMessage(int index) {
    chilkatJNI.CkEmail_RemoveAttachedMessage(swigCPtr, this, index);
  }

  public void GetLinkedDomains(CkStringArray array) {
    chilkatJNI.CkEmail_GetLinkedDomains(swigCPtr, this, CkStringArray.getCPtr(array), array);
  }

  public void UnSpamify() {
    chilkatJNI.CkEmail_UnSpamify(swigCPtr, this);
  }

  public boolean IsMultipartReport() {
    return chilkatJNI.CkEmail_IsMultipartReport(swigCPtr, this);
  }

  public boolean HasHtmlBody() {
    return chilkatJNI.CkEmail_HasHtmlBody(swigCPtr, this);
  }

  public boolean HasPlainTextBody() {
    return chilkatJNI.CkEmail_HasPlainTextBody(swigCPtr, this);
  }

  public void RemoveAttachmentPaths() {
    chilkatJNI.CkEmail_RemoveAttachmentPaths(swigCPtr, this);
  }

}
