/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkHttpRequest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkHttpRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkHttpRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkHttpRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkHttpRequest() {
    this(chilkatJNI.new_CkHttpRequest(), true);
  }

  public void RemoveAllParams() {
    chilkatJNI.CkHttpRequest_RemoveAllParams(swigCPtr, this);
  }

  public boolean LoadBodyFromFile(String filename) {
    return chilkatJNI.CkHttpRequest_LoadBodyFromFile(swigCPtr, this, filename);
  }

  public boolean LoadBodyFromBytes(CkByteData binaryData) {
    return chilkatJNI.CkHttpRequest_LoadBodyFromBytes(swigCPtr, this, CkByteData.getCPtr(binaryData), binaryData);
  }

  public boolean LoadBodyFromString(String bodyStr, String charset) {
    return chilkatJNI.CkHttpRequest_LoadBodyFromString(swigCPtr, this, bodyStr, charset);
  }

  public void UsePut() {
    chilkatJNI.CkHttpRequest_UsePut(swigCPtr, this);
  }

  public boolean AddBytesForUpload(String name, String filename, CkByteData byteData) {
    return chilkatJNI.CkHttpRequest_AddBytesForUpload(swigCPtr, this, name, filename, CkByteData.getCPtr(byteData), byteData);
  }

  public void UsePostMultipartForm() {
    chilkatJNI.CkHttpRequest_UsePostMultipartForm(swigCPtr, this);
  }

  public boolean GetUrlEncodedParams(CkString outStr) {
    return chilkatJNI.CkHttpRequest_GetUrlEncodedParams(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String getUrlEncodedParams() {
    return chilkatJNI.CkHttpRequest_getUrlEncodedParams(swigCPtr, this);
  }

  public boolean AddStringForUpload(String name, String filename, String strData, String charset) {
    return chilkatJNI.CkHttpRequest_AddStringForUpload(swigCPtr, this, name, filename, strData, charset);
  }

  public boolean AddFileForUpload2(String name, String filename, String contentType) {
    return chilkatJNI.CkHttpRequest_AddFileForUpload2(swigCPtr, this, name, filename, contentType);
  }

  public boolean AddStringForUpload2(String name, String filename, String strData, String charset, String contentType) {
    return chilkatJNI.CkHttpRequest_AddStringForUpload2(swigCPtr, this, name, filename, strData, charset, contentType);
  }

  public boolean AddBytesForUpload2(String name, String filename, CkByteData byteData, String contentType) {
    return chilkatJNI.CkHttpRequest_AddBytesForUpload2(swigCPtr, this, name, filename, CkByteData.getCPtr(byteData), byteData, contentType);
  }

  public void UseUploadPut() {
    chilkatJNI.CkHttpRequest_UseUploadPut(swigCPtr, this);
  }

  public void get_HttpVerb(CkString str) {
    chilkatJNI.CkHttpRequest_get_HttpVerb(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpVerb() {
    return chilkatJNI.CkHttpRequest_httpVerb(swigCPtr, this);
  }

  public void put_HttpVerb(String newVal) {
    chilkatJNI.CkHttpRequest_put_HttpVerb(swigCPtr, this, newVal);
  }

  public void get_ContentType(CkString str) {
    chilkatJNI.CkHttpRequest_get_ContentType(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String contentType() {
    return chilkatJNI.CkHttpRequest_contentType(swigCPtr, this);
  }

  public void put_ContentType(String newVal) {
    chilkatJNI.CkHttpRequest_put_ContentType(swigCPtr, this, newVal);
  }

  public void get_EntireHeader(CkString str) {
    chilkatJNI.CkHttpRequest_get_EntireHeader(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String entireHeader() {
    return chilkatJNI.CkHttpRequest_entireHeader(swigCPtr, this);
  }

  public void put_EntireHeader(String newVal) {
    chilkatJNI.CkHttpRequest_put_EntireHeader(swigCPtr, this, newVal);
  }

  public boolean StreamBodyFromFile(String filename) {
    return chilkatJNI.CkHttpRequest_StreamBodyFromFile(swigCPtr, this, filename);
  }

  public boolean RemoveHeader(String name) {
    return chilkatJNI.CkHttpRequest_RemoveHeader(swigCPtr, this, name);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkHttpRequest_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkHttpRequest_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkHttpRequest_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkHttpRequest_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkHttpRequest_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public String path() {
    return chilkatJNI.CkHttpRequest_path(swigCPtr, this);
  }

  public String charset() {
    return chilkatJNI.CkHttpRequest_charset(swigCPtr, this);
  }

  public String httpVersion() {
    return chilkatJNI.CkHttpRequest_httpVersion(swigCPtr, this);
  }

  public String getHeaderField(String name) {
    return chilkatJNI.CkHttpRequest_getHeaderField(swigCPtr, this, name);
  }

  public String getHeaderName(int index) {
    return chilkatJNI.CkHttpRequest_getHeaderName(swigCPtr, this, index);
  }

  public String getHeaderValue(int index) {
    return chilkatJNI.CkHttpRequest_getHeaderValue(swigCPtr, this, index);
  }

  public String getParam(String name) {
    return chilkatJNI.CkHttpRequest_getParam(swigCPtr, this, name);
  }

  public String getParamName(int index) {
    return chilkatJNI.CkHttpRequest_getParamName(swigCPtr, this, index);
  }

  public String getParamValue(int index) {
    return chilkatJNI.CkHttpRequest_getParamValue(swigCPtr, this, index);
  }

  public String lastErrorText() {
    return chilkatJNI.CkHttpRequest_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkHttpRequest_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkHttpRequest_lastErrorHtml(swigCPtr, this);
  }

  public void RemoveParam(String name) {
    chilkatJNI.CkHttpRequest_RemoveParam(swigCPtr, this, name);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkHttpRequest_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkHttpRequest_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkHttpRequest_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkHttpRequest_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void UsePost() {
    chilkatJNI.CkHttpRequest_UsePost(swigCPtr, this);
  }

  public void UseGet() {
    chilkatJNI.CkHttpRequest_UseGet(swigCPtr, this);
  }

  public void UseHead() {
    chilkatJNI.CkHttpRequest_UseHead(swigCPtr, this);
  }

  public void UseXmlHttp(String xmlBody) {
    chilkatJNI.CkHttpRequest_UseXmlHttp(swigCPtr, this, xmlBody);
  }

  public void UseUpload() {
    chilkatJNI.CkHttpRequest_UseUpload(swigCPtr, this);
  }

  public void SetFromUrl(String url) {
    chilkatJNI.CkHttpRequest_SetFromUrl(swigCPtr, this, url);
  }

  public void put_Path(String path) {
    chilkatJNI.CkHttpRequest_put_Path(swigCPtr, this, path);
  }

  public void get_Path(CkString str) {
    chilkatJNI.CkHttpRequest_get_Path(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Charset(String charset) {
    chilkatJNI.CkHttpRequest_put_Charset(swigCPtr, this, charset);
  }

  public void get_Charset(CkString str) {
    chilkatJNI.CkHttpRequest_get_Charset(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_SendCharset(boolean val) {
    chilkatJNI.CkHttpRequest_put_SendCharset(swigCPtr, this, val);
  }

  public boolean get_SendCharset() {
    return chilkatJNI.CkHttpRequest_get_SendCharset(swigCPtr, this);
  }

  public void put_HttpVersion(String version) {
    chilkatJNI.CkHttpRequest_put_HttpVersion(swigCPtr, this, version);
  }

  public void get_HttpVersion(CkString str) {
    chilkatJNI.CkHttpRequest_get_HttpVersion(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void AddHeader(String name, String value) {
    chilkatJNI.CkHttpRequest_AddHeader(swigCPtr, this, name, value);
  }

  public void AddParam(String name, String value) {
    chilkatJNI.CkHttpRequest_AddParam(swigCPtr, this, name, value);
  }

  public boolean AddFileForUpload(String name, String filename) {
    return chilkatJNI.CkHttpRequest_AddFileForUpload(swigCPtr, this, name, filename);
  }

  public void GenerateRequestText(CkString str) {
    chilkatJNI.CkHttpRequest_GenerateRequestText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String generateRequestText() {
    return chilkatJNI.CkHttpRequest_generateRequestText(swigCPtr, this);
  }

  public int get_NumHeaderFields() {
    return chilkatJNI.CkHttpRequest_get_NumHeaderFields(swigCPtr, this);
  }

  public boolean GetHeaderField(String name, CkString str) {
    return chilkatJNI.CkHttpRequest_GetHeaderField(swigCPtr, this, name, CkString.getCPtr(str), str);
  }

  public boolean GetHeaderName(int index, CkString str) {
    return chilkatJNI.CkHttpRequest_GetHeaderName(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetHeaderValue(int index, CkString str) {
    return chilkatJNI.CkHttpRequest_GetHeaderValue(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public int get_NumParams() {
    return chilkatJNI.CkHttpRequest_get_NumParams(swigCPtr, this);
  }

  public boolean GetParam(String name, CkString str) {
    return chilkatJNI.CkHttpRequest_GetParam(swigCPtr, this, name, CkString.getCPtr(str), str);
  }

  public boolean GetParamName(int index, CkString str) {
    return chilkatJNI.CkHttpRequest_GetParamName(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetParamValue(int index, CkString str) {
    return chilkatJNI.CkHttpRequest_GetParamValue(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

}
