/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkHttpResponse {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkHttpResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkHttpResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkHttpResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkHttpResponse() {
    this(chilkatJNI.new_CkHttpResponse(), true);
  }

  public boolean SaveBodyBinary(String path) {
    return chilkatJNI.CkHttpResponse_SaveBodyBinary(swigCPtr, this, path);
  }

  public boolean SaveBodyText(boolean bCrlf, String path) {
    return chilkatJNI.CkHttpResponse_SaveBodyText(swigCPtr, this, bCrlf, path);
  }

  public void get_DateStr(CkString str) {
    chilkatJNI.CkHttpResponse_get_DateStr(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String dateStr() {
    return chilkatJNI.CkHttpResponse_dateStr(swigCPtr, this);
  }

  public void get_FullMime(CkString str) {
    chilkatJNI.CkHttpResponse_get_FullMime(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String fullMime() {
    return chilkatJNI.CkHttpResponse_fullMime(swigCPtr, this);
  }

  public boolean UrlEncParamValue(String encodedParams, String paramName, CkString outStr) {
    return chilkatJNI.CkHttpResponse_UrlEncParamValue(swigCPtr, this, encodedParams, paramName, CkString.getCPtr(outStr), outStr);
  }

  public String urlEncParamValue(String encodedParams, String paramName) {
    return chilkatJNI.CkHttpResponse_urlEncParamValue(swigCPtr, this, encodedParams, paramName);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkHttpResponse_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkHttpResponse_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkHttpResponse_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkHttpResponse_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkHttpResponse_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkHttpResponse_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkHttpResponse_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkHttpResponse_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkHttpResponse_lastErrorHtml(swigCPtr, this);
  }

  public String lastErrorText() {
    return chilkatJNI.CkHttpResponse_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkHttpResponse_lastErrorXml(swigCPtr, this);
  }

  public String header() {
    return chilkatJNI.CkHttpResponse_header(swigCPtr, this);
  }

  public String bodyStr() {
    return chilkatJNI.CkHttpResponse_bodyStr(swigCPtr, this);
  }

  public String statusLine() {
    return chilkatJNI.CkHttpResponse_statusLine(swigCPtr, this);
  }

  public String charset() {
    return chilkatJNI.CkHttpResponse_charset(swigCPtr, this);
  }

  public String domain() {
    return chilkatJNI.CkHttpResponse_domain(swigCPtr, this);
  }

  public String getHeaderField(String fieldName) {
    return chilkatJNI.CkHttpResponse_getHeaderField(swigCPtr, this, fieldName);
  }

  public String getHeaderFieldAttr(String fieldName, String attrName) {
    return chilkatJNI.CkHttpResponse_getHeaderFieldAttr(swigCPtr, this, fieldName, attrName);
  }

  public String getHeaderName(int index) {
    return chilkatJNI.CkHttpResponse_getHeaderName(swigCPtr, this, index);
  }

  public String getHeaderValue(int index) {
    return chilkatJNI.CkHttpResponse_getHeaderValue(swigCPtr, this, index);
  }

  public String getCookieDomain(int index) {
    return chilkatJNI.CkHttpResponse_getCookieDomain(swigCPtr, this, index);
  }

  public String getCookiePath(int index) {
    return chilkatJNI.CkHttpResponse_getCookiePath(swigCPtr, this, index);
  }

  public String getCookieExpiresStr(int index) {
    return chilkatJNI.CkHttpResponse_getCookieExpiresStr(swigCPtr, this, index);
  }

  public String getCookieName(int index) {
    return chilkatJNI.CkHttpResponse_getCookieName(swigCPtr, this, index);
  }

  public String getCookieValue(int index) {
    return chilkatJNI.CkHttpResponse_getCookieValue(swigCPtr, this, index);
  }

  public void get_Header(CkString str) {
    chilkatJNI.CkHttpResponse_get_Header(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_Body(CkByteData data) {
    chilkatJNI.CkHttpResponse_get_Body(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public void get_BodyStr(CkString str) {
    chilkatJNI.CkHttpResponse_get_BodyStr(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_BodyQP(CkString str) {
    chilkatJNI.CkHttpResponse_get_BodyQP(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_StatusLine(CkString str) {
    chilkatJNI.CkHttpResponse_get_StatusLine(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public int get_StatusCode() {
    return chilkatJNI.CkHttpResponse_get_StatusCode(swigCPtr, this);
  }

  public void get_Charset(CkString str) {
    chilkatJNI.CkHttpResponse_get_Charset(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_Domain(CkString str) {
    chilkatJNI.CkHttpResponse_get_Domain(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public int get_ContentLength() {
    return chilkatJNI.CkHttpResponse_get_ContentLength(swigCPtr, this);
  }

  public void get_Date(SYSTEMTIME sysTime) {
    chilkatJNI.CkHttpResponse_get_Date(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public boolean GetHeaderField(String fieldName, CkString str) {
    return chilkatJNI.CkHttpResponse_GetHeaderField(swigCPtr, this, fieldName, CkString.getCPtr(str), str);
  }

  public boolean GetHeaderFieldAttr(String fieldName, String attrName, CkString str) {
    return chilkatJNI.CkHttpResponse_GetHeaderFieldAttr(swigCPtr, this, fieldName, attrName, CkString.getCPtr(str), str);
  }

  public int get_NumHeaderFields() {
    return chilkatJNI.CkHttpResponse_get_NumHeaderFields(swigCPtr, this);
  }

  public boolean GetHeaderName(int index, CkString str) {
    return chilkatJNI.CkHttpResponse_GetHeaderName(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetHeaderValue(int index, CkString str) {
    return chilkatJNI.CkHttpResponse_GetHeaderValue(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public int get_NumCookies() {
    return chilkatJNI.CkHttpResponse_get_NumCookies(swigCPtr, this);
  }

  public boolean GetCookieDomain(int index, CkString str) {
    return chilkatJNI.CkHttpResponse_GetCookieDomain(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetCookiePath(int index, CkString str) {
    return chilkatJNI.CkHttpResponse_GetCookiePath(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetCookieExpiresStr(int index, CkString str) {
    return chilkatJNI.CkHttpResponse_GetCookieExpiresStr(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetCookieExpires(int index, SYSTEMTIME outSysTime) {
    return chilkatJNI.CkHttpResponse_GetCookieExpires(swigCPtr, this, index, SYSTEMTIME.getCPtr(outSysTime), outSysTime);
  }

  public boolean GetCookieName(int index, CkString str) {
    return chilkatJNI.CkHttpResponse_GetCookieName(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

  public boolean GetCookieValue(int index, CkString str) {
    return chilkatJNI.CkHttpResponse_GetCookieValue(swigCPtr, this, index, CkString.getCPtr(str), str);
  }

}
