/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkMailboxes {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkMailboxes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkMailboxes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkMailboxes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkMailboxes() {
    this(chilkatJNI.new_CkMailboxes(), true);
  }

  public boolean IsMarked(int index) {
    return chilkatJNI.CkMailboxes_IsMarked(swigCPtr, this, index);
  }

  public boolean HasInferiors(int index) {
    return chilkatJNI.CkMailboxes_HasInferiors(swigCPtr, this, index);
  }

  public boolean IsSelectable(int index) {
    return chilkatJNI.CkMailboxes_IsSelectable(swigCPtr, this, index);
  }

  public boolean GetName(int index, CkString strName) {
    return chilkatJNI.CkMailboxes_GetName(swigCPtr, this, index, CkString.getCPtr(strName), strName);
  }

  public int get_Count() {
    return chilkatJNI.CkMailboxes_get_Count(swigCPtr, this);
  }

  public String getName(int index) {
    return chilkatJNI.CkMailboxes_getName(swigCPtr, this, index);
  }

}
