/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkMime {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkMime(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkMime obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkMime(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkMime() {
    this(chilkatJNI.new_CkMime(), true);
  }

  public void Convert8Bit() {
    chilkatJNI.CkMime_Convert8Bit(swigCPtr, this);
  }

  public boolean get_UseMmDescription() {
    return chilkatJNI.CkMime_get_UseMmDescription(swigCPtr, this);
  }

  public void put_UseMmDescription(boolean newVal) {
    chilkatJNI.CkMime_put_UseMmDescription(swigCPtr, this, newVal);
  }

  public boolean GetMimeBytes(CkByteData outBytes) {
    return chilkatJNI.CkMime_GetMimeBytes(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public CkStringArray ExtractPartsToFiles(String dirPath) {
    long cPtr = chilkatJNI.CkMime_ExtractPartsToFiles(swigCPtr, this, dirPath);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, false);
  }

  public boolean AsnBodyToXml(CkString outStr) {
    return chilkatJNI.CkMime_AsnBodyToXml(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String asnBodyToXml() {
    return chilkatJNI.CkMime_asnBodyToXml(swigCPtr, this);
  }

  public void get_CurrentDateTime(CkString str) {
    chilkatJNI.CkMime_get_CurrentDateTime(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String currentDateTime() {
    return chilkatJNI.CkMime_currentDateTime(swigCPtr, this);
  }

  public boolean EncryptN() {
    return chilkatJNI.CkMime_EncryptN(swigCPtr, this);
  }

  public boolean AddEncryptCert(CkCert cert) {
    return chilkatJNI.CkMime_AddEncryptCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public void ClearEncryptCerts() {
    chilkatJNI.CkMime_ClearEncryptCerts(swigCPtr, this);
  }

  public void SetBody(String str) {
    chilkatJNI.CkMime_SetBody(swigCPtr, this, str);
  }

  public void UrlEncodeBody(String charset) {
    chilkatJNI.CkMime_UrlEncodeBody(swigCPtr, this, charset);
  }

  public void AddContentLength() {
    chilkatJNI.CkMime_AddContentLength(swigCPtr, this);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkMime_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkMime_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean DecryptUsingPfxData(CkByteData pfxData, String password) {
    return chilkatJNI.CkMime_DecryptUsingPfxData(swigCPtr, this, CkByteData.getCPtr(pfxData), pfxData, password);
  }

  public boolean DecryptUsingPfxFile(String pfxFilePath, String password) {
    return chilkatJNI.CkMime_DecryptUsingPfxFile(swigCPtr, this, pfxFilePath, password);
  }

  public boolean AddPfxSourceData(CkByteData pfxData, String password) {
    return chilkatJNI.CkMime_AddPfxSourceData(swigCPtr, this, CkByteData.getCPtr(pfxData), pfxData, password);
  }

  public boolean AddPfxSourceFile(String pfxFilePath, String password) {
    return chilkatJNI.CkMime_AddPfxSourceFile(swigCPtr, this, pfxFilePath, password);
  }

  public void get_Pkcs7CryptAlg(CkString str) {
    chilkatJNI.CkMime_get_Pkcs7CryptAlg(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String pkcs7CryptAlg() {
    return chilkatJNI.CkMime_pkcs7CryptAlg(swigCPtr, this);
  }

  public void put_Pkcs7CryptAlg(String newVal) {
    chilkatJNI.CkMime_put_Pkcs7CryptAlg(swigCPtr, this, newVal);
  }

  public int get_Pkcs7KeyLength() {
    return chilkatJNI.CkMime_get_Pkcs7KeyLength(swigCPtr, this);
  }

  public void put_Pkcs7KeyLength(int newVal) {
    chilkatJNI.CkMime_put_Pkcs7KeyLength(swigCPtr, this, newVal);
  }

  public void get_SigningHashAlg(CkString str) {
    chilkatJNI.CkMime_get_SigningHashAlg(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String signingHashAlg() {
    return chilkatJNI.CkMime_signingHashAlg(swigCPtr, this);
  }

  public void put_SigningHashAlg(String newVal) {
    chilkatJNI.CkMime_put_SigningHashAlg(swigCPtr, this, newVal);
  }

  public boolean GetHeaderFieldAttribute(String name, String attrName, CkString outStr) {
    return chilkatJNI.CkMime_GetHeaderFieldAttribute(swigCPtr, this, name, attrName, CkString.getCPtr(outStr), outStr);
  }

  public String getHeaderFieldAttribute(String name, String attrName) {
    return chilkatJNI.CkMime_getHeaderFieldAttribute(swigCPtr, this, name, attrName);
  }

  public boolean HasSignatureSigningTime(int index) {
    return chilkatJNI.CkMime_HasSignatureSigningTime(swigCPtr, this, index);
  }

  public boolean GetSignatureSigningTime(int index, SYSTEMTIME outSysTime) {
    return chilkatJNI.CkMime_GetSignatureSigningTime(swigCPtr, this, index, SYSTEMTIME.getCPtr(outSysTime), outSysTime);
  }

  public void RemoveHeaderField(String name, boolean bAllOccurances) {
    chilkatJNI.CkMime_RemoveHeaderField(swigCPtr, this, name, bAllOccurances);
  }

  public boolean get_UseXPkcs7() {
    return chilkatJNI.CkMime_get_UseXPkcs7(swigCPtr, this);
  }

  public void put_UseXPkcs7(boolean newVal) {
    chilkatJNI.CkMime_put_UseXPkcs7(swigCPtr, this, newVal);
  }

  public CkCert FindIssuer(CkCert cert) {
    long cPtr = chilkatJNI.CkMime_FindIssuer(swigCPtr, this, CkCert.getCPtr(cert), cert);
    return (cPtr == 0) ? null : new CkCert(cPtr, false);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkMime_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkMime_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkMime_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean GetSignatureSigningTimeStr(int index, CkString outStr) {
    return chilkatJNI.CkMime_GetSignatureSigningTimeStr(swigCPtr, this, index, CkString.getCPtr(outStr), outStr);
  }

  public String getSignatureSigningTimeStr(int index) {
    return chilkatJNI.CkMime_getSignatureSigningTimeStr(swigCPtr, this, index);
  }

  public String entireHead() {
    return chilkatJNI.CkMime_entireHead(swigCPtr, this);
  }

  public String entireBody() {
    return chilkatJNI.CkMime_entireBody(swigCPtr, this);
  }

  public String xml() {
    return chilkatJNI.CkMime_xml(swigCPtr, this);
  }

  public String mime() {
    return chilkatJNI.CkMime_mime(swigCPtr, this);
  }

  public String bodyEncoded() {
    return chilkatJNI.CkMime_bodyEncoded(swigCPtr, this);
  }

  public String bodyDecoded() {
    return chilkatJNI.CkMime_bodyDecoded(swigCPtr, this);
  }

  public String charset() {
    return chilkatJNI.CkMime_charset(swigCPtr, this);
  }

  public String disposition() {
    return chilkatJNI.CkMime_disposition(swigCPtr, this);
  }

  public String encoding() {
    return chilkatJNI.CkMime_encoding(swigCPtr, this);
  }

  public String contentType() {
    return chilkatJNI.CkMime_contentType(swigCPtr, this);
  }

  public String filename() {
    return chilkatJNI.CkMime_filename(swigCPtr, this);
  }

  public String name() {
    return chilkatJNI.CkMime_name(swigCPtr, this);
  }

  public String boundary() {
    return chilkatJNI.CkMime_boundary(swigCPtr, this);
  }

  public String micalg() {
    return chilkatJNI.CkMime_micalg(swigCPtr, this);
  }

  public String protocol() {
    return chilkatJNI.CkMime_protocol(swigCPtr, this);
  }

  public String version() {
    return chilkatJNI.CkMime_version(swigCPtr, this);
  }

  public String header(String name) {
    return chilkatJNI.CkMime_header(swigCPtr, this, name);
  }

  public String headerName(int index) {
    return chilkatJNI.CkMime_headerName(swigCPtr, this, index);
  }

  public String headerValue(int index) {
    return chilkatJNI.CkMime_headerValue(swigCPtr, this, index);
  }

  public String getHeaderField(String name) {
    return chilkatJNI.CkMime_getHeaderField(swigCPtr, this, name);
  }

  public String getHeaderFieldName(int index) {
    return chilkatJNI.CkMime_getHeaderFieldName(swigCPtr, this, index);
  }

  public String getHeaderFieldValue(int index) {
    return chilkatJNI.CkMime_getHeaderFieldValue(swigCPtr, this, index);
  }

  public String getEntireHead() {
    return chilkatJNI.CkMime_getEntireHead(swigCPtr, this);
  }

  public String getEntireBody() {
    return chilkatJNI.CkMime_getEntireBody(swigCPtr, this);
  }

  public String getXml() {
    return chilkatJNI.CkMime_getXml(swigCPtr, this);
  }

  public String getMime() {
    return chilkatJNI.CkMime_getMime(swigCPtr, this);
  }

  public String getBodyEncoded() {
    return chilkatJNI.CkMime_getBodyEncoded(swigCPtr, this);
  }

  public String getBodyDecoded() {
    return chilkatJNI.CkMime_getBodyDecoded(swigCPtr, this);
  }

  public String lastErrorText() {
    return chilkatJNI.CkMime_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkMime_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkMime_lastErrorHtml(swigCPtr, this);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkMime_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkMime_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkMime_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkMime_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkMime_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean AddDetachedSignaturePk(CkCert cert, CkPrivateKey privateKey) {
    return chilkatJNI.CkMime_AddDetachedSignaturePk(swigCPtr, this, CkCert.getCPtr(cert), cert, CkPrivateKey.getCPtr(privateKey), privateKey);
  }

  public boolean AddDetachedSignaturePk2(CkCert cert, CkPrivateKey privateKey, boolean transferHeaderFields) {
    return chilkatJNI.CkMime_AddDetachedSignaturePk2(swigCPtr, this, CkCert.getCPtr(cert), cert, CkPrivateKey.getCPtr(privateKey), privateKey, transferHeaderFields);
  }

  public boolean ConvertToSignedPk(CkCert cert, CkPrivateKey privateKey) {
    return chilkatJNI.CkMime_ConvertToSignedPk(swigCPtr, this, CkCert.getCPtr(cert), cert, CkPrivateKey.getCPtr(privateKey), privateKey);
  }

  public boolean Decrypt() {
    return chilkatJNI.CkMime_Decrypt(swigCPtr, this);
  }

  public boolean Decrypt2(CkCert cert, CkPrivateKey privateKey) {
    return chilkatJNI.CkMime_Decrypt2(swigCPtr, this, CkCert.getCPtr(cert), cert, CkPrivateKey.getCPtr(privateKey), privateKey);
  }

  public boolean Verify() {
    return chilkatJNI.CkMime_Verify(swigCPtr, this);
  }

  public void ConvertToMultipartMixed() {
    chilkatJNI.CkMime_ConvertToMultipartMixed(swigCPtr, this);
  }

  public void ConvertToMultipartAlt() {
    chilkatJNI.CkMime_ConvertToMultipartAlt(swigCPtr, this);
  }

  public boolean SetBodyFromPlainText(String str) {
    return chilkatJNI.CkMime_SetBodyFromPlainText(swigCPtr, this, str);
  }

  public boolean SetHeaderField(String name, String value) {
    return chilkatJNI.CkMime_SetHeaderField(swigCPtr, this, name, value);
  }

  public boolean GetHeaderField(String name, CkString value) {
    return chilkatJNI.CkMime_GetHeaderField(swigCPtr, this, name, CkString.getCPtr(value), value);
  }

  public boolean GetHeaderFieldName(int index, CkString fieldName) {
    return chilkatJNI.CkMime_GetHeaderFieldName(swigCPtr, this, index, CkString.getCPtr(fieldName), fieldName);
  }

  public boolean GetHeaderFieldValue(int index, CkString fieldValue) {
    return chilkatJNI.CkMime_GetHeaderFieldValue(swigCPtr, this, index, CkString.getCPtr(fieldValue), fieldValue);
  }

  public boolean AddDetachedSignature2(CkCert cert, boolean transferHeaderFields) {
    return chilkatJNI.CkMime_AddDetachedSignature2(swigCPtr, this, CkCert.getCPtr(cert), cert, transferHeaderFields);
  }

  public boolean AddHeaderField(String name, String value) {
    return chilkatJNI.CkMime_AddHeaderField(swigCPtr, this, name, value);
  }

  public void SetVerifyCert(CkCert cert) {
    chilkatJNI.CkMime_SetVerifyCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean LoadMimeFile(String fileName) {
    return chilkatJNI.CkMime_LoadMimeFile(swigCPtr, this, fileName);
  }

  public boolean LoadMime(String mimeMsg) {
    return chilkatJNI.CkMime_LoadMime(swigCPtr, this, mimeMsg);
  }

  public boolean SaveMime(String filename) {
    return chilkatJNI.CkMime_SaveMime(swigCPtr, this, filename);
  }

  public int get_NumParts() {
    return chilkatJNI.CkMime_get_NumParts(swigCPtr, this);
  }

  public CkMime GetPart(int index) {
    long cPtr = chilkatJNI.CkMime_GetPart(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkMime(cPtr, true);
  }

  public void get_Protocol(CkString str) {
    chilkatJNI.CkMime_get_Protocol(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Protocol(String newVal) {
    chilkatJNI.CkMime_put_Protocol(swigCPtr, this, newVal);
  }

  public void get_Micalg(CkString str) {
    chilkatJNI.CkMime_get_Micalg(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Micalg(String newVal) {
    chilkatJNI.CkMime_put_Micalg(swigCPtr, this, newVal);
  }

  public void get_Boundary(CkString str) {
    chilkatJNI.CkMime_get_Boundary(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Boundary(String newVal) {
    chilkatJNI.CkMime_put_Boundary(swigCPtr, this, newVal);
  }

  public void get_Name(CkString str) {
    chilkatJNI.CkMime_get_Name(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Name(String newVal) {
    chilkatJNI.CkMime_put_Name(swigCPtr, this, newVal);
  }

  public void get_Filename(CkString str) {
    chilkatJNI.CkMime_get_Filename(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Filename(String newVal) {
    chilkatJNI.CkMime_put_Filename(swigCPtr, this, newVal);
  }

  public void get_Charset(CkString sb) {
    chilkatJNI.CkMime_get_Charset(swigCPtr, this, CkString.getCPtr(sb), sb);
  }

  public void put_Charset(String newVal) {
    chilkatJNI.CkMime_put_Charset(swigCPtr, this, newVal);
  }

  public void get_Disposition(CkString str) {
    chilkatJNI.CkMime_get_Disposition(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Disposition(String newVal) {
    chilkatJNI.CkMime_put_Disposition(swigCPtr, this, newVal);
  }

  public void get_Encoding(CkString str) {
    chilkatJNI.CkMime_get_Encoding(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Encoding(String newVal) {
    chilkatJNI.CkMime_put_Encoding(swigCPtr, this, newVal);
  }

  public void get_ContentType(CkString str) {
    chilkatJNI.CkMime_get_ContentType(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_ContentType(String newVal) {
    chilkatJNI.CkMime_put_ContentType(swigCPtr, this, newVal);
  }

  public boolean UnlockComponent(String unlockCode) {
    return chilkatJNI.CkMime_UnlockComponent(swigCPtr, this, unlockCode);
  }

  public boolean IsUnlocked() {
    return chilkatJNI.CkMime_IsUnlocked(swigCPtr, this);
  }

  public int get_NumHeaderFields() {
    return chilkatJNI.CkMime_get_NumHeaderFields(swigCPtr, this);
  }

  public int get_NumSignerCerts() {
    return chilkatJNI.CkMime_get_NumSignerCerts(swigCPtr, this);
  }

  public int get_NumEncryptCerts() {
    return chilkatJNI.CkMime_get_NumEncryptCerts(swigCPtr, this);
  }

  public boolean get_UnwrapExtras() {
    return chilkatJNI.CkMime_get_UnwrapExtras(swigCPtr, this);
  }

  public void put_UnwrapExtras(boolean newVal) {
    chilkatJNI.CkMime_put_UnwrapExtras(swigCPtr, this, newVal);
  }

  public boolean AppendPart(CkMime mime) {
    return chilkatJNI.CkMime_AppendPart(swigCPtr, this, CkMime.getCPtr(mime), mime);
  }

  public boolean AppendPartFromFile(String filename) {
    return chilkatJNI.CkMime_AppendPartFromFile(swigCPtr, this, filename);
  }

  public boolean NewMultipartMixed() {
    return chilkatJNI.CkMime_NewMultipartMixed(swigCPtr, this);
  }

  public boolean NewMultipartRelated() {
    return chilkatJNI.CkMime_NewMultipartRelated(swigCPtr, this);
  }

  public boolean NewMultipartAlternative() {
    return chilkatJNI.CkMime_NewMultipartAlternative(swigCPtr, this);
  }

  public boolean NewMessageRfc822(CkMime mimeObject) {
    return chilkatJNI.CkMime_NewMessageRfc822(swigCPtr, this, CkMime.getCPtr(mimeObject), mimeObject);
  }

  public boolean SaveBody(String filename) {
    return chilkatJNI.CkMime_SaveBody(swigCPtr, this, filename);
  }

  public boolean IsMultipart() {
    return chilkatJNI.CkMime_IsMultipart(swigCPtr, this);
  }

  public boolean IsPlainText() {
    return chilkatJNI.CkMime_IsPlainText(swigCPtr, this);
  }

  public boolean IsHtml() {
    return chilkatJNI.CkMime_IsHtml(swigCPtr, this);
  }

  public boolean IsXml() {
    return chilkatJNI.CkMime_IsXml(swigCPtr, this);
  }

  public boolean IsSigned() {
    return chilkatJNI.CkMime_IsSigned(swigCPtr, this);
  }

  public boolean IsEncrypted() {
    return chilkatJNI.CkMime_IsEncrypted(swigCPtr, this);
  }

  public boolean IsMultipartMixed() {
    return chilkatJNI.CkMime_IsMultipartMixed(swigCPtr, this);
  }

  public boolean IsMultipartAlternative() {
    return chilkatJNI.CkMime_IsMultipartAlternative(swigCPtr, this);
  }

  public boolean IsMultipartRelated() {
    return chilkatJNI.CkMime_IsMultipartRelated(swigCPtr, this);
  }

  public boolean IsAttachment() {
    return chilkatJNI.CkMime_IsAttachment(swigCPtr, this);
  }

  public boolean IsText() {
    return chilkatJNI.CkMime_IsText(swigCPtr, this);
  }

  public boolean IsApplicationData() {
    return chilkatJNI.CkMime_IsApplicationData(swigCPtr, this);
  }

  public boolean IsImage() {
    return chilkatJNI.CkMime_IsImage(swigCPtr, this);
  }

  public boolean IsAudio() {
    return chilkatJNI.CkMime_IsAudio(swigCPtr, this);
  }

  public boolean IsVideo() {
    return chilkatJNI.CkMime_IsVideo(swigCPtr, this);
  }

  public boolean GetBodyBinary(CkByteData db) {
    return chilkatJNI.CkMime_GetBodyBinary(swigCPtr, this, CkByteData.getCPtr(db), db);
  }

  public boolean GetBodyEncoded(CkString encodedBody) {
    return chilkatJNI.CkMime_GetBodyEncoded(swigCPtr, this, CkString.getCPtr(encodedBody), encodedBody);
  }

  public boolean GetBodyDecoded(CkString decodedBody) {
    return chilkatJNI.CkMime_GetBodyDecoded(swigCPtr, this, CkString.getCPtr(decodedBody), decodedBody);
  }

  public boolean SetBodyFromEncoded(String encoding, String str) {
    return chilkatJNI.CkMime_SetBodyFromEncoded(swigCPtr, this, encoding, str);
  }

  public boolean SetBodyFromHtml(String str) {
    return chilkatJNI.CkMime_SetBodyFromHtml(swigCPtr, this, str);
  }

  public boolean SetBodyFromXml(String str) {
    return chilkatJNI.CkMime_SetBodyFromXml(swigCPtr, this, str);
  }

  public boolean SetBodyFromBinary(CkByteData dbuf) {
    return chilkatJNI.CkMime_SetBodyFromBinary(swigCPtr, this, CkByteData.getCPtr(dbuf), dbuf);
  }

  public boolean SetBodyFromFile(String fileName) {
    return chilkatJNI.CkMime_SetBodyFromFile(swigCPtr, this, fileName);
  }

  public boolean Encrypt(CkCert cert) {
    return chilkatJNI.CkMime_Encrypt(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean ConvertToSigned(CkCert cert) {
    return chilkatJNI.CkMime_ConvertToSigned(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean AddDetachedSignature(CkCert cert) {
    return chilkatJNI.CkMime_AddDetachedSignature(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean SaveXml(String filename) {
    return chilkatJNI.CkMime_SaveXml(swigCPtr, this, filename);
  }

  public boolean GetMime(CkString mime) {
    return chilkatJNI.CkMime_GetMime(swigCPtr, this, CkString.getCPtr(mime), mime);
  }

  public boolean GetXml(CkString xml) {
    return chilkatJNI.CkMime_GetXml(swigCPtr, this, CkString.getCPtr(xml), xml);
  }

  public boolean LoadXml(String xml) {
    return chilkatJNI.CkMime_LoadXml(swigCPtr, this, xml);
  }

  public CkCert GetEncryptCert(int index) {
    long cPtr = chilkatJNI.CkMime_GetEncryptCert(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkCert GetSignerCert(int index) {
    long cPtr = chilkatJNI.CkMime_GetSignerCert(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public boolean UnwrapSecurity() {
    return chilkatJNI.CkMime_UnwrapSecurity(swigCPtr, this);
  }

  public boolean LoadXmlFile(String fileName) {
    return chilkatJNI.CkMime_LoadXmlFile(swigCPtr, this, fileName);
  }

  public void GetEntireHead(CkString str) {
    chilkatJNI.CkMime_GetEntireHead(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void GetEntireBody(CkString str) {
    chilkatJNI.CkMime_GetEntireBody(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean RemovePart(int index) {
    return chilkatJNI.CkMime_RemovePart(swigCPtr, this, index);
  }

  public boolean ContainsEncryptedParts() {
    return chilkatJNI.CkMime_ContainsEncryptedParts(swigCPtr, this);
  }

  public boolean ContainsSignedParts() {
    return chilkatJNI.CkMime_ContainsSignedParts(swigCPtr, this);
  }

}
