/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkOmaDrm {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkOmaDrm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkOmaDrm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkOmaDrm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkOmaDrm() {
    this(chilkatJNI.new_CkOmaDrm(), true);
  }

  public boolean UnlockComponent(String unlockCode) {
    return chilkatJNI.CkOmaDrm_UnlockComponent(swigCPtr, this, unlockCode);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkOmaDrm_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkOmaDrm_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkOmaDrm_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkOmaDrm_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean LoadDcfFile(String filename) {
    return chilkatJNI.CkOmaDrm_LoadDcfFile(swigCPtr, this, filename);
  }

  public boolean LoadDcfData(CkByteData data) {
    return chilkatJNI.CkOmaDrm_LoadDcfData(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public void get_Base64Key(CkString str) {
    chilkatJNI.CkOmaDrm_get_Base64Key(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Base64Key(String key) {
    chilkatJNI.CkOmaDrm_put_Base64Key(swigCPtr, this, key);
  }

  public int get_DrmContentVersion() {
    return chilkatJNI.CkOmaDrm_get_DrmContentVersion(swigCPtr, this);
  }

  public void get_ContentType(CkString str) {
    chilkatJNI.CkOmaDrm_get_ContentType(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_ContentType(String contentType) {
    chilkatJNI.CkOmaDrm_put_ContentType(swigCPtr, this, contentType);
  }

  public void get_ContentUri(CkString str) {
    chilkatJNI.CkOmaDrm_get_ContentUri(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_ContentUri(String contentUri) {
    chilkatJNI.CkOmaDrm_put_ContentUri(swigCPtr, this, contentUri);
  }

  public void get_Headers(CkString str) {
    chilkatJNI.CkOmaDrm_get_Headers(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Headers(String headers) {
    chilkatJNI.CkOmaDrm_put_Headers(swigCPtr, this, headers);
  }

  public void get_IV(CkByteData data) {
    chilkatJNI.CkOmaDrm_get_IV(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public void put_IV(CkByteData data) {
    chilkatJNI.CkOmaDrm_put_IV(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public void get_EncryptedData(CkByteData data) {
    chilkatJNI.CkOmaDrm_get_EncryptedData(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public void get_DecryptedData(CkByteData data) {
    chilkatJNI.CkOmaDrm_get_DecryptedData(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean SaveDecrypted(String filename) {
    return chilkatJNI.CkOmaDrm_SaveDecrypted(swigCPtr, this, filename);
  }

  public boolean GetHeaderField(String fieldName, CkString fieldVal) {
    return chilkatJNI.CkOmaDrm_GetHeaderField(swigCPtr, this, fieldName, CkString.getCPtr(fieldVal), fieldVal);
  }

  public void LoadUnencryptedData(CkByteData data) {
    chilkatJNI.CkOmaDrm_LoadUnencryptedData(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadUnencryptedFile(String filename) {
    return chilkatJNI.CkOmaDrm_LoadUnencryptedFile(swigCPtr, this, filename);
  }

  public void SetEncodedIV(String encodedIv, String encoding) {
    chilkatJNI.CkOmaDrm_SetEncodedIV(swigCPtr, this, encodedIv, encoding);
  }

  public boolean CreateDcfFile(String filename) {
    return chilkatJNI.CkOmaDrm_CreateDcfFile(swigCPtr, this, filename);
  }

  public String lastErrorText() {
    return chilkatJNI.CkOmaDrm_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkOmaDrm_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkOmaDrm_lastErrorHtml(swigCPtr, this);
  }

  public String base64Key() {
    return chilkatJNI.CkOmaDrm_base64Key(swigCPtr, this);
  }

  public String contentType() {
    return chilkatJNI.CkOmaDrm_contentType(swigCPtr, this);
  }

  public String contentUri() {
    return chilkatJNI.CkOmaDrm_contentUri(swigCPtr, this);
  }

  public String headers() {
    return chilkatJNI.CkOmaDrm_headers(swigCPtr, this);
  }

  public String getHeaderField(String fieldName) {
    return chilkatJNI.CkOmaDrm_getHeaderField(swigCPtr, this, fieldName);
  }

}
