/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkPrivateKey {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkPrivateKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkPrivateKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkPrivateKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkPrivateKey() {
    this(chilkatJNI.new_CkPrivateKey(), true);
  }

  public boolean LoadEncryptedPem(String pemStr, String password) {
    return chilkatJNI.CkPrivateKey_LoadEncryptedPem(swigCPtr, this, pemStr, password);
  }

  public boolean LoadEncryptedPemFile(String filename, String password) {
    return chilkatJNI.CkPrivateKey_LoadEncryptedPemFile(swigCPtr, this, filename, password);
  }

  public boolean LoadPkcs8Encrypted(CkByteData data, String password) {
    return chilkatJNI.CkPrivateKey_LoadPkcs8Encrypted(swigCPtr, this, CkByteData.getCPtr(data), data, password);
  }

  public boolean LoadPkcs8EncryptedFile(String filename, String password) {
    return chilkatJNI.CkPrivateKey_LoadPkcs8EncryptedFile(swigCPtr, this, filename, password);
  }

  public boolean GetPkcs8Encrypted(String password, CkByteData outBytes) {
    return chilkatJNI.CkPrivateKey_GetPkcs8Encrypted(swigCPtr, this, password, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean GetPkcs8EncryptedPem(String password, CkString outStr) {
    return chilkatJNI.CkPrivateKey_GetPkcs8EncryptedPem(swigCPtr, this, password, CkString.getCPtr(outStr), outStr);
  }

  public String getPkcs8EncryptedPem(String password) {
    return chilkatJNI.CkPrivateKey_getPkcs8EncryptedPem(swigCPtr, this, password);
  }

  public boolean SavePkcs8EncryptedFile(String password, String filename) {
    return chilkatJNI.CkPrivateKey_SavePkcs8EncryptedFile(swigCPtr, this, password, filename);
  }

  public boolean SavePkcs8EncryptedPemFile(String password, String filename) {
    return chilkatJNI.CkPrivateKey_SavePkcs8EncryptedPemFile(swigCPtr, this, password, filename);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkPrivateKey_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkPrivateKey_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkPrivateKey_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkPrivateKey_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkPrivateKey_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean LoadRsaDerFile(String filename) {
    return chilkatJNI.CkPrivateKey_LoadRsaDerFile(swigCPtr, this, filename);
  }

  public boolean LoadPkcs8File(String filename) {
    return chilkatJNI.CkPrivateKey_LoadPkcs8File(swigCPtr, this, filename);
  }

  public boolean LoadPemFile(String filename) {
    return chilkatJNI.CkPrivateKey_LoadPemFile(swigCPtr, this, filename);
  }

  public boolean LoadXmlFile(String filename) {
    return chilkatJNI.CkPrivateKey_LoadXmlFile(swigCPtr, this, filename);
  }

  public boolean LoadPem(String str) {
    return chilkatJNI.CkPrivateKey_LoadPem(swigCPtr, this, str);
  }

  public boolean LoadRsaDer(CkByteData data) {
    return chilkatJNI.CkPrivateKey_LoadRsaDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadPkcs8(CkByteData data) {
    return chilkatJNI.CkPrivateKey_LoadPkcs8(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadXml(String xml) {
    return chilkatJNI.CkPrivateKey_LoadXml(swigCPtr, this, xml);
  }

  public boolean SaveRsaDerFile(String filename) {
    return chilkatJNI.CkPrivateKey_SaveRsaDerFile(swigCPtr, this, filename);
  }

  public boolean SavePkcs8File(String filename) {
    return chilkatJNI.CkPrivateKey_SavePkcs8File(swigCPtr, this, filename);
  }

  public boolean SaveRsaPemFile(String filename) {
    return chilkatJNI.CkPrivateKey_SaveRsaPemFile(swigCPtr, this, filename);
  }

  public boolean SavePkcs8PemFile(String filename) {
    return chilkatJNI.CkPrivateKey_SavePkcs8PemFile(swigCPtr, this, filename);
  }

  public boolean SaveXmlFile(String filename) {
    return chilkatJNI.CkPrivateKey_SaveXmlFile(swigCPtr, this, filename);
  }

  public boolean GetRsaDer(CkByteData data) {
    return chilkatJNI.CkPrivateKey_GetRsaDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean GetPkcs8(CkByteData data) {
    return chilkatJNI.CkPrivateKey_GetPkcs8(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean GetRsaPem(CkString str) {
    return chilkatJNI.CkPrivateKey_GetRsaPem(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean GetPkcs8Pem(CkString str) {
    return chilkatJNI.CkPrivateKey_GetPkcs8Pem(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean GetXml(CkString str) {
    return chilkatJNI.CkPrivateKey_GetXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkPrivateKey_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkPrivateKey_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkPrivateKey_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkPrivateKey_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkPrivateKey_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkPrivateKey_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkPrivateKey_lastErrorHtml(swigCPtr, this);
  }

  public String getRsaPem() {
    return chilkatJNI.CkPrivateKey_getRsaPem(swigCPtr, this);
  }

  public String getPkcs8Pem() {
    return chilkatJNI.CkPrivateKey_getPkcs8Pem(swigCPtr, this);
  }

  public String getXml() {
    return chilkatJNI.CkPrivateKey_getXml(swigCPtr, this);
  }

}
