/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkPublicKey {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkPublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkPublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkPublicKey() {
    this(chilkatJNI.new_CkPublicKey(), true);
  }

  public boolean LoadPkcs1Pem(String str) {
    return chilkatJNI.CkPublicKey_LoadPkcs1Pem(swigCPtr, this, str);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkPublicKey_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkPublicKey_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkPublicKey_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkPublicKey_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkPublicKey_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean LoadRsaDerFile(String filename) {
    return chilkatJNI.CkPublicKey_LoadRsaDerFile(swigCPtr, this, filename);
  }

  public boolean LoadOpenSslDerFile(String filename) {
    return chilkatJNI.CkPublicKey_LoadOpenSslDerFile(swigCPtr, this, filename);
  }

  public boolean LoadOpenSslPemFile(String filename) {
    return chilkatJNI.CkPublicKey_LoadOpenSslPemFile(swigCPtr, this, filename);
  }

  public boolean LoadXmlFile(String filename) {
    return chilkatJNI.CkPublicKey_LoadXmlFile(swigCPtr, this, filename);
  }

  public boolean LoadOpenSslPem(String str) {
    return chilkatJNI.CkPublicKey_LoadOpenSslPem(swigCPtr, this, str);
  }

  public boolean LoadOpenSslDer(CkByteData data) {
    return chilkatJNI.CkPublicKey_LoadOpenSslDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadRsaDer(CkByteData data) {
    return chilkatJNI.CkPublicKey_LoadRsaDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadXml(String xml) {
    return chilkatJNI.CkPublicKey_LoadXml(swigCPtr, this, xml);
  }

  public boolean SaveRsaDerFile(String filename) {
    return chilkatJNI.CkPublicKey_SaveRsaDerFile(swigCPtr, this, filename);
  }

  public boolean SaveOpenSslDerFile(String filename) {
    return chilkatJNI.CkPublicKey_SaveOpenSslDerFile(swigCPtr, this, filename);
  }

  public boolean SaveOpenSslPemFile(String filename) {
    return chilkatJNI.CkPublicKey_SaveOpenSslPemFile(swigCPtr, this, filename);
  }

  public boolean SaveXmlFile(String filename) {
    return chilkatJNI.CkPublicKey_SaveXmlFile(swigCPtr, this, filename);
  }

  public boolean GetRsaDer(CkByteData data) {
    return chilkatJNI.CkPublicKey_GetRsaDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean GetOpenSslDer(CkByteData data) {
    return chilkatJNI.CkPublicKey_GetOpenSslDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean GetOpenSslPem(CkString str) {
    return chilkatJNI.CkPublicKey_GetOpenSslPem(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean GetXml(CkString str) {
    return chilkatJNI.CkPublicKey_GetXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkPublicKey_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkPublicKey_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkPublicKey_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkPublicKey_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkPublicKey_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkPublicKey_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkPublicKey_lastErrorHtml(swigCPtr, this);
  }

  public String getOpenSslPem() {
    return chilkatJNI.CkPublicKey_getOpenSslPem(swigCPtr, this);
  }

  public String getXml() {
    return chilkatJNI.CkPublicKey_getXml(swigCPtr, this);
  }

}
