/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkSFtpDir {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkSFtpDir(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkSFtpDir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkSFtpDir(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkSFtpDir() {
    this(chilkatJNI.new_CkSFtpDir(), true);
  }

  public boolean get_Utf8() {
    return chilkatJNI.CkSFtpDir_get_Utf8(swigCPtr, this);
  }

  public void put_Utf8(boolean b) {
    chilkatJNI.CkSFtpDir_put_Utf8(swigCPtr, this, b);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkSFtpDir_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkSFtpDir_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkSFtpDir_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkSFtpDir_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkSFtpDir_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkSFtpDir_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkSFtpDir_lastErrorHtml(swigCPtr, this);
  }

  public int get_NumFilesAndDirs() {
    return chilkatJNI.CkSFtpDir_get_NumFilesAndDirs(swigCPtr, this);
  }

  public void get_OriginalPath(CkString str) {
    chilkatJNI.CkSFtpDir_get_OriginalPath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String originalPath() {
    return chilkatJNI.CkSFtpDir_originalPath(swigCPtr, this);
  }

  public CkSFtpFile GetFileObject(int index) {
    long cPtr = chilkatJNI.CkSFtpDir_GetFileObject(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkSFtpFile(cPtr, true);
  }

  public boolean GetFilename(int index, CkString outStr) {
    return chilkatJNI.CkSFtpDir_GetFilename(swigCPtr, this, index, CkString.getCPtr(outStr), outStr);
  }

  public String getFilename(int index) {
    return chilkatJNI.CkSFtpDir_getFilename(swigCPtr, this, index);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkSFtpDir_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkSFtpDir_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkSFtpDir_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkSFtpDir_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkSFtpDir_put_VerboseLogging(swigCPtr, this, newVal);
  }

}
