/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkSshTunnel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkSshTunnel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkSshTunnel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkSshTunnel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkSshTunnel() {
    this(chilkatJNI.new_CkSshTunnel(), true);
  }

  public boolean get_Utf8() {
    return chilkatJNI.CkSshTunnel_get_Utf8(swigCPtr, this);
  }

  public void put_Utf8(boolean b) {
    chilkatJNI.CkSshTunnel_put_Utf8(swigCPtr, this, b);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkSshTunnel_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkSshTunnel_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkSshTunnel_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkSshTunnel_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkSshTunnel_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkSshTunnel_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkSshTunnel_lastErrorHtml(swigCPtr, this);
  }

  public boolean UnlockComponent(String unlockCode) {
    return chilkatJNI.CkSshTunnel_UnlockComponent(swigCPtr, this, unlockCode);
  }

  public void get_SshLogin(CkString str) {
    chilkatJNI.CkSshTunnel_get_SshLogin(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sshLogin() {
    return chilkatJNI.CkSshTunnel_sshLogin(swigCPtr, this);
  }

  public void put_SshLogin(String newVal) {
    chilkatJNI.CkSshTunnel_put_SshLogin(swigCPtr, this, newVal);
  }

  public void get_SshPassword(CkString str) {
    chilkatJNI.CkSshTunnel_get_SshPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sshPassword() {
    return chilkatJNI.CkSshTunnel_sshPassword(swigCPtr, this);
  }

  public void put_SshPassword(String newVal) {
    chilkatJNI.CkSshTunnel_put_SshPassword(swigCPtr, this, newVal);
  }

  public void get_ConnectLog(CkString str) {
    chilkatJNI.CkSshTunnel_get_ConnectLog(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String connectLog() {
    return chilkatJNI.CkSshTunnel_connectLog(swigCPtr, this);
  }

  public void put_ConnectLog(String newVal) {
    chilkatJNI.CkSshTunnel_put_ConnectLog(swigCPtr, this, newVal);
  }

  public void get_DestHostname(CkString str) {
    chilkatJNI.CkSshTunnel_get_DestHostname(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String destHostname() {
    return chilkatJNI.CkSshTunnel_destHostname(swigCPtr, this);
  }

  public void put_DestHostname(String newVal) {
    chilkatJNI.CkSshTunnel_put_DestHostname(swigCPtr, this, newVal);
  }

  public void get_SshHostname(CkString str) {
    chilkatJNI.CkSshTunnel_get_SshHostname(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sshHostname() {
    return chilkatJNI.CkSshTunnel_sshHostname(swigCPtr, this);
  }

  public void put_SshHostname(String newVal) {
    chilkatJNI.CkSshTunnel_put_SshHostname(swigCPtr, this, newVal);
  }

  public int get_SshPort() {
    return chilkatJNI.CkSshTunnel_get_SshPort(swigCPtr, this);
  }

  public void put_SshPort(int newVal) {
    chilkatJNI.CkSshTunnel_put_SshPort(swigCPtr, this, newVal);
  }

  public int get_DestPort() {
    return chilkatJNI.CkSshTunnel_get_DestPort(swigCPtr, this);
  }

  public void put_DestPort(int newVal) {
    chilkatJNI.CkSshTunnel_put_DestPort(swigCPtr, this, newVal);
  }

  public boolean get_IsAccepting() {
    return chilkatJNI.CkSshTunnel_get_IsAccepting(swigCPtr, this);
  }

  public boolean StopAllTunnels(int maxWaitMs) {
    return chilkatJNI.CkSshTunnel_StopAllTunnels(swigCPtr, this, maxWaitMs);
  }

  public boolean GetTunnelsXml(CkString outStr) {
    return chilkatJNI.CkSshTunnel_GetTunnelsXml(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String getTunnelsXml() {
    return chilkatJNI.CkSshTunnel_getTunnelsXml(swigCPtr, this);
  }

  public boolean StopAccepting() {
    return chilkatJNI.CkSshTunnel_StopAccepting(swigCPtr, this);
  }

  public boolean BeginAccepting(int listenPort) {
    return chilkatJNI.CkSshTunnel_BeginAccepting(swigCPtr, this, listenPort);
  }

  public boolean SetSshAuthenticationKey(CkSshKey key) {
    return chilkatJNI.CkSshTunnel_SetSshAuthenticationKey(swigCPtr, this, CkSshKey.getCPtr(key), key);
  }

  public void get_ListenBindIpAddress(CkString str) {
    chilkatJNI.CkSshTunnel_get_ListenBindIpAddress(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String listenBindIpAddress() {
    return chilkatJNI.CkSshTunnel_listenBindIpAddress(swigCPtr, this);
  }

  public void put_ListenBindIpAddress(String newVal) {
    chilkatJNI.CkSshTunnel_put_ListenBindIpAddress(swigCPtr, this, newVal);
  }

  public void get_OutboundBindIpAddress(CkString str) {
    chilkatJNI.CkSshTunnel_get_OutboundBindIpAddress(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String outboundBindIpAddress() {
    return chilkatJNI.CkSshTunnel_outboundBindIpAddress(swigCPtr, this);
  }

  public void put_OutboundBindIpAddress(String newVal) {
    chilkatJNI.CkSshTunnel_put_OutboundBindIpAddress(swigCPtr, this, newVal);
  }

  public int get_OutboundBindPort() {
    return chilkatJNI.CkSshTunnel_get_OutboundBindPort(swigCPtr, this);
  }

  public void put_OutboundBindPort(int newVal) {
    chilkatJNI.CkSshTunnel_put_OutboundBindPort(swigCPtr, this, newVal);
  }

  public int get_MaxPacketSize() {
    return chilkatJNI.CkSshTunnel_get_MaxPacketSize(swigCPtr, this);
  }

  public void put_MaxPacketSize(int newVal) {
    chilkatJNI.CkSshTunnel_put_MaxPacketSize(swigCPtr, this, newVal);
  }

  public boolean get_TcpNoDelay() {
    return chilkatJNI.CkSshTunnel_get_TcpNoDelay(swigCPtr, this);
  }

  public void put_TcpNoDelay(boolean newVal) {
    chilkatJNI.CkSshTunnel_put_TcpNoDelay(swigCPtr, this, newVal);
  }

  public void get_HttpProxyHostname(CkString str) {
    chilkatJNI.CkSshTunnel_get_HttpProxyHostname(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyHostname() {
    return chilkatJNI.CkSshTunnel_httpProxyHostname(swigCPtr, this);
  }

  public void put_HttpProxyHostname(String newVal) {
    chilkatJNI.CkSshTunnel_put_HttpProxyHostname(swigCPtr, this, newVal);
  }

  public void get_HttpProxyUsername(CkString str) {
    chilkatJNI.CkSshTunnel_get_HttpProxyUsername(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyUsername() {
    return chilkatJNI.CkSshTunnel_httpProxyUsername(swigCPtr, this);
  }

  public void put_HttpProxyUsername(String newVal) {
    chilkatJNI.CkSshTunnel_put_HttpProxyUsername(swigCPtr, this, newVal);
  }

  public void get_HttpProxyPassword(CkString str) {
    chilkatJNI.CkSshTunnel_get_HttpProxyPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyPassword() {
    return chilkatJNI.CkSshTunnel_httpProxyPassword(swigCPtr, this);
  }

  public void put_HttpProxyPassword(String newVal) {
    chilkatJNI.CkSshTunnel_put_HttpProxyPassword(swigCPtr, this, newVal);
  }

  public void get_HttpProxyAuthMethod(CkString str) {
    chilkatJNI.CkSshTunnel_get_HttpProxyAuthMethod(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyAuthMethod() {
    return chilkatJNI.CkSshTunnel_httpProxyAuthMethod(swigCPtr, this);
  }

  public void put_HttpProxyAuthMethod(String newVal) {
    chilkatJNI.CkSshTunnel_put_HttpProxyAuthMethod(swigCPtr, this, newVal);
  }

  public int get_HttpProxyPort() {
    return chilkatJNI.CkSshTunnel_get_HttpProxyPort(swigCPtr, this);
  }

  public void put_HttpProxyPort(int newVal) {
    chilkatJNI.CkSshTunnel_put_HttpProxyPort(swigCPtr, this, newVal);
  }

  public int get_SocksPort() {
    return chilkatJNI.CkSshTunnel_get_SocksPort(swigCPtr, this);
  }

  public void put_SocksPort(int newVal) {
    chilkatJNI.CkSshTunnel_put_SocksPort(swigCPtr, this, newVal);
  }

  public void get_SocksHostname(CkString str) {
    chilkatJNI.CkSshTunnel_get_SocksHostname(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String socksHostname() {
    return chilkatJNI.CkSshTunnel_socksHostname(swigCPtr, this);
  }

  public void put_SocksHostname(String newVal) {
    chilkatJNI.CkSshTunnel_put_SocksHostname(swigCPtr, this, newVal);
  }

  public void get_SocksUsername(CkString str) {
    chilkatJNI.CkSshTunnel_get_SocksUsername(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String socksUsername() {
    return chilkatJNI.CkSshTunnel_socksUsername(swigCPtr, this);
  }

  public void put_SocksUsername(String newVal) {
    chilkatJNI.CkSshTunnel_put_SocksUsername(swigCPtr, this, newVal);
  }

  public void get_SocksPassword(CkString str) {
    chilkatJNI.CkSshTunnel_get_SocksPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String socksPassword() {
    return chilkatJNI.CkSshTunnel_socksPassword(swigCPtr, this);
  }

  public void put_SocksPassword(String newVal) {
    chilkatJNI.CkSshTunnel_put_SocksPassword(swigCPtr, this, newVal);
  }

  public int get_SocksVersion() {
    return chilkatJNI.CkSshTunnel_get_SocksVersion(swigCPtr, this);
  }

  public void put_SocksVersion(int newVal) {
    chilkatJNI.CkSshTunnel_put_SocksVersion(swigCPtr, this, newVal);
  }

  public int get_ConnectTimeoutMs() {
    return chilkatJNI.CkSshTunnel_get_ConnectTimeoutMs(swigCPtr, this);
  }

  public void put_ConnectTimeoutMs(int newVal) {
    chilkatJNI.CkSshTunnel_put_ConnectTimeoutMs(swigCPtr, this, newVal);
  }

  public int get_ListenPort() {
    return chilkatJNI.CkSshTunnel_get_ListenPort(swigCPtr, this);
  }

  public void get_TunnelThreadSessionLogPath(CkString str) {
    chilkatJNI.CkSshTunnel_get_TunnelThreadSessionLogPath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String tunnelThreadSessionLogPath() {
    return chilkatJNI.CkSshTunnel_tunnelThreadSessionLogPath(swigCPtr, this);
  }

  public void put_TunnelThreadSessionLogPath(String newVal) {
    chilkatJNI.CkSshTunnel_put_TunnelThreadSessionLogPath(swigCPtr, this, newVal);
  }

  public void get_AcceptThreadSessionLogPath(CkString str) {
    chilkatJNI.CkSshTunnel_get_AcceptThreadSessionLogPath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String acceptThreadSessionLogPath() {
    return chilkatJNI.CkSshTunnel_acceptThreadSessionLogPath(swigCPtr, this);
  }

  public void put_AcceptThreadSessionLogPath(String newVal) {
    chilkatJNI.CkSshTunnel_put_AcceptThreadSessionLogPath(swigCPtr, this, newVal);
  }

  public void ClearTunnelErrors() {
    chilkatJNI.CkSshTunnel_ClearTunnelErrors(swigCPtr, this);
  }

  public void get_TunnelErrors(CkString str) {
    chilkatJNI.CkSshTunnel_get_TunnelErrors(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String tunnelErrors() {
    return chilkatJNI.CkSshTunnel_tunnelErrors(swigCPtr, this);
  }

  public void get_HttpProxyDomain(CkString str) {
    chilkatJNI.CkSshTunnel_get_HttpProxyDomain(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyDomain() {
    return chilkatJNI.CkSshTunnel_httpProxyDomain(swigCPtr, this);
  }

  public void put_HttpProxyDomain(String newVal) {
    chilkatJNI.CkSshTunnel_put_HttpProxyDomain(swigCPtr, this, newVal);
  }

  public int get_IdleTimeoutMs() {
    return chilkatJNI.CkSshTunnel_get_IdleTimeoutMs(swigCPtr, this);
  }

  public void put_IdleTimeoutMs(int newVal) {
    chilkatJNI.CkSshTunnel_put_IdleTimeoutMs(swigCPtr, this, newVal);
  }

  public int get_SoSndBuf() {
    return chilkatJNI.CkSshTunnel_get_SoSndBuf(swigCPtr, this);
  }

  public void put_SoSndBuf(int newVal) {
    chilkatJNI.CkSshTunnel_put_SoSndBuf(swigCPtr, this, newVal);
  }

  public int get_SoRcvBuf() {
    return chilkatJNI.CkSshTunnel_get_SoRcvBuf(swigCPtr, this);
  }

  public void put_SoRcvBuf(int newVal) {
    chilkatJNI.CkSshTunnel_put_SoRcvBuf(swigCPtr, this, newVal);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkSshTunnel_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkSshTunnel_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkSshTunnel_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkSshTunnel_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkSshTunnel_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean get_KeepConnectLog() {
    return chilkatJNI.CkSshTunnel_get_KeepConnectLog(swigCPtr, this);
  }

  public void put_KeepConnectLog(boolean newVal) {
    chilkatJNI.CkSshTunnel_put_KeepConnectLog(swigCPtr, this, newVal);
  }

}
