/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkStringArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkStringArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkStringArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkStringArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkStringArray() {
    this(chilkatJNI.new_CkStringArray(), true);
  }

  public void LoadFromText(String str) {
    chilkatJNI.CkStringArray_LoadFromText(swigCPtr, this, str);
  }

  public boolean SaveNthToFile(int index, String filename) {
    return chilkatJNI.CkStringArray_SaveNthToFile(swigCPtr, this, index, filename);
  }

  public int FindFirstMatch(String str, int firstIndex) {
    return chilkatJNI.CkStringArray_FindFirstMatch(swigCPtr, this, str, firstIndex);
  }

  public void Union(CkStringArray array) {
    chilkatJNI.CkStringArray_Union(swigCPtr, this, CkStringArray.getCPtr(array), array);
  }

  public int GetStringLen(int index) {
    return chilkatJNI.CkStringArray_GetStringLen(swigCPtr, this, index);
  }

  public boolean LoadFromFile2(String filename, String charset) {
    return chilkatJNI.CkStringArray_LoadFromFile2(swigCPtr, this, filename, charset);
  }

  public boolean SaveToFile2(String filename, String charset) {
    return chilkatJNI.CkStringArray_SaveToFile2(swigCPtr, this, filename, charset);
  }

  public void SplitAndAppend(String str, String boundary) {
    chilkatJNI.CkStringArray_SplitAndAppend(swigCPtr, this, str, boundary);
  }

  public void Append(String str) {
    chilkatJNI.CkStringArray_Append(swigCPtr, this, str);
  }

  public boolean LoadFromFile(String filename) {
    return chilkatJNI.CkStringArray_LoadFromFile(swigCPtr, this, filename);
  }

  public boolean SaveToFile(String filename) {
    return chilkatJNI.CkStringArray_SaveToFile(swigCPtr, this, filename);
  }

  public boolean RemoveAt(int index) {
    return chilkatJNI.CkStringArray_RemoveAt(swigCPtr, this, index);
  }

  public void InsertAt(int index, String str) {
    chilkatJNI.CkStringArray_InsertAt(swigCPtr, this, index, str);
  }

  public int Find(String str, int firstIndex) {
    return chilkatJNI.CkStringArray_Find(swigCPtr, this, str, firstIndex);
  }

  public void Prepend(String str) {
    chilkatJNI.CkStringArray_Prepend(swigCPtr, this, str);
  }

  public boolean AppendSerialized(String encodedStr) {
    return chilkatJNI.CkStringArray_AppendSerialized(swigCPtr, this, encodedStr);
  }

  public void Remove(String str) {
    chilkatJNI.CkStringArray_Remove(swigCPtr, this, str);
  }

  public boolean Contains(String str) {
    return chilkatJNI.CkStringArray_Contains(swigCPtr, this, str);
  }

  public void Clear() {
    chilkatJNI.CkStringArray_Clear(swigCPtr, this);
  }

  public void Sort(boolean ascending) {
    chilkatJNI.CkStringArray_Sort(swigCPtr, this, ascending);
  }

  public String pop() {
    return chilkatJNI.CkStringArray_pop(swigCPtr, this);
  }

  public String getString(int index) {
    return chilkatJNI.CkStringArray_getString(swigCPtr, this, index);
  }

  public String lastString() {
    return chilkatJNI.CkStringArray_lastString(swigCPtr, this);
  }

  public String strAt(int index) {
    return chilkatJNI.CkStringArray_strAt(swigCPtr, this, index);
  }

  public String serialize() {
    return chilkatJNI.CkStringArray_serialize(swigCPtr, this);
  }

  public String saveToText() {
    return chilkatJNI.CkStringArray_saveToText(swigCPtr, this);
  }

  public void Serialize(CkString outStr) {
    chilkatJNI.CkStringArray_Serialize(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public boolean GetString(int index, CkString outStr) {
    return chilkatJNI.CkStringArray_GetString(swigCPtr, this, index, CkString.getCPtr(outStr), outStr);
  }

  public boolean LastString(CkString outStr) {
    return chilkatJNI.CkStringArray_LastString(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public boolean Pop(CkString outStr) {
    return chilkatJNI.CkStringArray_Pop(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public void SaveToText(CkString outStr) {
    chilkatJNI.CkStringArray_SaveToText(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public int get_Count() {
    return chilkatJNI.CkStringArray_get_Count(swigCPtr, this);
  }

  public boolean get_Crlf() {
    return chilkatJNI.CkStringArray_get_Crlf(swigCPtr, this);
  }

  public void put_Crlf(boolean newVal) {
    chilkatJNI.CkStringArray_put_Crlf(swigCPtr, this, newVal);
  }

  public boolean get_Trim() {
    return chilkatJNI.CkStringArray_get_Trim(swigCPtr, this);
  }

  public void put_Trim(boolean newVal) {
    chilkatJNI.CkStringArray_put_Trim(swigCPtr, this, newVal);
  }

  public boolean get_Unique() {
    return chilkatJNI.CkStringArray_get_Unique(swigCPtr, this);
  }

  public void put_Unique(boolean newVal) {
    chilkatJNI.CkStringArray_put_Unique(swigCPtr, this, newVal);
  }

}
