/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkXmp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkXmp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkXmp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkXmp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkXmp() {
    this(chilkatJNI.new_CkXmp(), true);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkXmp_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkXmp_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkXmp_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkXmp_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkXmp_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public String lastErrorText() {
    return chilkatJNI.CkXmp_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkXmp_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkXmp_lastErrorHtml(swigCPtr, this);
  }

  public String getSimpleStr(CkXml xml, String propName) {
    return chilkatJNI.CkXmp_getSimpleStr(swigCPtr, this, CkXml.getCPtr(xml), xml, propName);
  }

  public String getStructValue(CkXml xml, String structName, String propName) {
    return chilkatJNI.CkXmp_getStructValue(swigCPtr, this, CkXml.getCPtr(xml), xml, structName, propName);
  }

  public String simpleStr(CkXml xml, String propName) {
    return chilkatJNI.CkXmp_simpleStr(swigCPtr, this, CkXml.getCPtr(xml), xml, propName);
  }

  public String structValue(CkXml xml, String structName, String propName) {
    return chilkatJNI.CkXmp_structValue(swigCPtr, this, CkXml.getCPtr(xml), xml, structName, propName);
  }

  public String version() {
    return chilkatJNI.CkXmp_version(swigCPtr, this);
  }

  public String dateToString(SYSTEMTIME sysTime) {
    return chilkatJNI.CkXmp_dateToString(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public boolean LoadFromBuffer(CkByteData byteData, String ext) {
    return chilkatJNI.CkXmp_LoadFromBuffer(swigCPtr, this, CkByteData.getCPtr(byteData), byteData, ext);
  }

  public boolean SaveToBuffer(CkByteData byteData) {
    return chilkatJNI.CkXmp_SaveToBuffer(swigCPtr, this, CkByteData.getCPtr(byteData), byteData);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkXmp_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkXmp_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkXmp_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkXmp_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean UnlockComponent(String unlockCode) {
    return chilkatJNI.CkXmp_UnlockComponent(swigCPtr, this, unlockCode);
  }

  public void get_Version(CkString strOut) {
    chilkatJNI.CkXmp_get_Version(swigCPtr, this, CkString.getCPtr(strOut), strOut);
  }

  public int get_NumEmbedded() {
    return chilkatJNI.CkXmp_get_NumEmbedded(swigCPtr, this);
  }

  public boolean LoadAppFile(String filename) {
    return chilkatJNI.CkXmp_LoadAppFile(swigCPtr, this, filename);
  }

  public boolean SaveAppFile(String filename) {
    return chilkatJNI.CkXmp_SaveAppFile(swigCPtr, this, filename);
  }

  public CkXml GetEmbedded(int index) {
    long cPtr = chilkatJNI.CkXmp_GetEmbedded(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkXml(cPtr, true);
  }

  public boolean GetSimpleStr(CkXml xml, String propName, CkString strOut) {
    return chilkatJNI.CkXmp_GetSimpleStr(swigCPtr, this, CkXml.getCPtr(xml), xml, propName, CkString.getCPtr(strOut), strOut);
  }

  public int GetSimpleInt(CkXml xml, String propName) {
    return chilkatJNI.CkXmp_GetSimpleInt(swigCPtr, this, CkXml.getCPtr(xml), xml, propName);
  }

  public boolean GetSimpleDate(CkXml xml, String propName, SYSTEMTIME outSysTime) {
    return chilkatJNI.CkXmp_GetSimpleDate(swigCPtr, this, CkXml.getCPtr(xml), xml, propName, SYSTEMTIME.getCPtr(outSysTime), outSysTime);
  }

  public boolean AddSimpleStr(CkXml xml, String propName, String propVal) {
    return chilkatJNI.CkXmp_AddSimpleStr(swigCPtr, this, CkXml.getCPtr(xml), xml, propName, propVal);
  }

  public boolean AddSimpleInt(CkXml xml, String propName, int propVal) {
    return chilkatJNI.CkXmp_AddSimpleInt(swigCPtr, this, CkXml.getCPtr(xml), xml, propName, propVal);
  }

  public boolean AddSimpleDate(CkXml xml, String propName, SYSTEMTIME sysTime) {
    return chilkatJNI.CkXmp_AddSimpleDate(swigCPtr, this, CkXml.getCPtr(xml), xml, propName, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public void AddNsMapping(String ns, String uri) {
    chilkatJNI.CkXmp_AddNsMapping(swigCPtr, this, ns, uri);
  }

  public void RemoveNsMapping(String ns) {
    chilkatJNI.CkXmp_RemoveNsMapping(swigCPtr, this, ns);
  }

  public CkXml NewXmp() {
    long cPtr = chilkatJNI.CkXmp_NewXmp(swigCPtr, this);
    return (cPtr == 0) ? null : new CkXml(cPtr, true);
  }

  public boolean StringToDate(String str, SYSTEMTIME outSysTime) {
    return chilkatJNI.CkXmp_StringToDate(swigCPtr, this, str, SYSTEMTIME.getCPtr(outSysTime), outSysTime);
  }

  public boolean DateToString(SYSTEMTIME sysTime, CkString outStr) {
    return chilkatJNI.CkXmp_DateToString(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime, CkString.getCPtr(outStr), outStr);
  }

  public boolean RemoveSimple(CkXml xml, String propName) {
    return chilkatJNI.CkXmp_RemoveSimple(swigCPtr, this, CkXml.getCPtr(xml), xml, propName);
  }

  public boolean Append(CkXml xml) {
    return chilkatJNI.CkXmp_Append(swigCPtr, this, CkXml.getCPtr(xml), xml);
  }

  public void RemoveAllEmbedded() {
    chilkatJNI.CkXmp_RemoveAllEmbedded(swigCPtr, this);
  }

  public void RemoveEmbedded(int index) {
    chilkatJNI.CkXmp_RemoveEmbedded(swigCPtr, this, index);
  }

  public boolean get_StructInnerDescrip() {
    return chilkatJNI.CkXmp_get_StructInnerDescrip(swigCPtr, this);
  }

  public void put_StructInnerDescrip(boolean val) {
    chilkatJNI.CkXmp_put_StructInnerDescrip(swigCPtr, this, val);
  }

  public CkXml GetProperty(CkXml xml, String propName) {
    long cPtr = chilkatJNI.CkXmp_GetProperty(swigCPtr, this, CkXml.getCPtr(xml), xml, propName);
    return (cPtr == 0) ? null : new CkXml(cPtr, true);
  }

  public CkStringArray GetArray(CkXml xml, String propName) {
    long cPtr = chilkatJNI.CkXmp_GetArray(swigCPtr, this, CkXml.getCPtr(xml), xml, propName);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public boolean RemoveArray(CkXml xml, String propName) {
    return chilkatJNI.CkXmp_RemoveArray(swigCPtr, this, CkXml.getCPtr(xml), xml, propName);
  }

  public boolean AddArray(CkXml xml, String arrType, String propName, CkStringArray values) {
    return chilkatJNI.CkXmp_AddArray(swigCPtr, this, CkXml.getCPtr(xml), xml, arrType, propName, CkStringArray.getCPtr(values), values);
  }

  public boolean GetStructValue(CkXml xml, String structName, String propName, CkString strOut) {
    return chilkatJNI.CkXmp_GetStructValue(swigCPtr, this, CkXml.getCPtr(xml), xml, structName, propName, CkString.getCPtr(strOut), strOut);
  }

  public CkStringArray GetStructPropNames(CkXml xml, String structName) {
    long cPtr = chilkatJNI.CkXmp_GetStructPropNames(swigCPtr, this, CkXml.getCPtr(xml), xml, structName);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public boolean RemoveStruct(CkXml xml, String structName) {
    return chilkatJNI.CkXmp_RemoveStruct(swigCPtr, this, CkXml.getCPtr(xml), xml, structName);
  }

  public boolean RemoveStructProp(CkXml xml, String structName, String propName) {
    return chilkatJNI.CkXmp_RemoveStructProp(swigCPtr, this, CkXml.getCPtr(xml), xml, structName, propName);
  }

  public boolean AddStructProp(CkXml xml, String structName, String propName, String propVal) {
    return chilkatJNI.CkXmp_AddStructProp(swigCPtr, this, CkXml.getCPtr(xml), xml, structName, propName, propVal);
  }

}
