/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkZipEntry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CkZipEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CkZipEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkZipEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkZipEntry() {
    this(chilkatJNI.new_CkZipEntry(), true);
  }

  public CkDateTime GetDt() {
    long cPtr = chilkatJNI.CkZipEntry_GetDt(swigCPtr, this);
    return (cPtr == 0) ? null : new CkDateTime(cPtr, false);
  }

  public void SetDt(CkDateTime dt) {
    chilkatJNI.CkZipEntry_SetDt(swigCPtr, this, CkDateTime.getCPtr(dt), dt);
  }

  public void get_FileDateTimeStr(CkString str) {
    chilkatJNI.CkZipEntry_get_FileDateTimeStr(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String fileDateTimeStr() {
    return chilkatJNI.CkZipEntry_fileDateTimeStr(swigCPtr, this);
  }

  public void put_FileDateTimeStr(String newVal) {
    chilkatJNI.CkZipEntry_put_FileDateTimeStr(swigCPtr, this, newVal);
  }

  public boolean AppendString(String inStr, String charset) {
    return chilkatJNI.CkZipEntry_AppendString(swigCPtr, this, inStr, charset);
  }

  public boolean ReplaceString(String inStr, String charset) {
    return chilkatJNI.CkZipEntry_ReplaceString(swigCPtr, this, inStr, charset);
  }

  public boolean UnzipToString(int lineEndingBehavior, String srcCharset, CkString outStr) {
    return chilkatJNI.CkZipEntry_UnzipToString(swigCPtr, this, lineEndingBehavior, srcCharset, CkString.getCPtr(outStr), outStr);
  }

  public String unzipToString(int lineEndingBehavior, String srcCharset) {
    return chilkatJNI.CkZipEntry_unzipToString(swigCPtr, this, lineEndingBehavior, srcCharset);
  }

  public String lastErrorText() {
    return chilkatJNI.CkZipEntry_lastErrorText(swigCPtr, this);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkZipEntry_lastErrorXml(swigCPtr, this);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkZipEntry_lastErrorHtml(swigCPtr, this);
  }

  public String fileName() {
    return chilkatJNI.CkZipEntry_fileName(swigCPtr, this);
  }

  public String comment() {
    return chilkatJNI.CkZipEntry_comment(swigCPtr, this);
  }

  public String copyToBase64() {
    return chilkatJNI.CkZipEntry_copyToBase64(swigCPtr, this);
  }

  public String copyToHex() {
    return chilkatJNI.CkZipEntry_copyToHex(swigCPtr, this);
  }

  public void get_FileName(CkString str) {
    chilkatJNI.CkZipEntry_get_FileName(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_FileName(String pStr) {
    chilkatJNI.CkZipEntry_put_FileName(swigCPtr, this, pStr);
  }

  public int get_UncompressedLength() {
    return chilkatJNI.CkZipEntry_get_UncompressedLength(swigCPtr, this);
  }

  public int get_CompressionLevel() {
    return chilkatJNI.CkZipEntry_get_CompressionLevel(swigCPtr, this);
  }

  public void put_CompressionLevel(int newVal) {
    chilkatJNI.CkZipEntry_put_CompressionLevel(swigCPtr, this, newVal);
  }

  public int get_CompressionMethod() {
    return chilkatJNI.CkZipEntry_get_CompressionMethod(swigCPtr, this);
  }

  public void put_CompressionMethod(int newVal) {
    chilkatJNI.CkZipEntry_put_CompressionMethod(swigCPtr, this, newVal);
  }

  public int get_CompressedLength() {
    return chilkatJNI.CkZipEntry_get_CompressedLength(swigCPtr, this);
  }

  public void get_Comment(CkString str) {
    chilkatJNI.CkZipEntry_get_Comment(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_Comment(String pStr) {
    chilkatJNI.CkZipEntry_put_Comment(swigCPtr, this, pStr);
  }

  public int get_EntryType() {
    return chilkatJNI.CkZipEntry_get_EntryType(swigCPtr, this);
  }

  public void get_FileDateTime(SYSTEMTIME sysTime) {
    chilkatJNI.CkZipEntry_get_FileDateTime(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public void put_FileDateTime(SYSTEMTIME sysTime) {
    chilkatJNI.CkZipEntry_put_FileDateTime(swigCPtr, this, SYSTEMTIME.getCPtr(sysTime), sysTime);
  }

  public boolean get_IsDirectory() {
    return chilkatJNI.CkZipEntry_get_IsDirectory(swigCPtr, this);
  }

  public int get_EntryID() {
    return chilkatJNI.CkZipEntry_get_EntryID(swigCPtr, this);
  }

  public boolean Extract(String dirPath) {
    return chilkatJNI.CkZipEntry_Extract(swigCPtr, this, dirPath);
  }

  public boolean ExtractInto(String dirPath) {
    return chilkatJNI.CkZipEntry_ExtractInto(swigCPtr, this, dirPath);
  }

  public boolean Inflate(CkByteData bdata) {
    return chilkatJNI.CkZipEntry_Inflate(swigCPtr, this, CkByteData.getCPtr(bdata), bdata);
  }

  public boolean ReplaceData(CkByteData bdata) {
    return chilkatJNI.CkZipEntry_ReplaceData(swigCPtr, this, CkByteData.getCPtr(bdata), bdata);
  }

  public boolean AppendData(CkByteData bdata) {
    return chilkatJNI.CkZipEntry_AppendData(swigCPtr, this, CkByteData.getCPtr(bdata), bdata);
  }

  public boolean CopyToBase64(CkString str) {
    return chilkatJNI.CkZipEntry_CopyToBase64(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean CopyToHex(CkString str) {
    return chilkatJNI.CkZipEntry_CopyToHex(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public boolean Copy(CkByteData bdata) {
    return chilkatJNI.CkZipEntry_Copy(swigCPtr, this, CkByteData.getCPtr(bdata), bdata);
  }

  public CkZipEntry NextEntry() {
    long cPtr = chilkatJNI.CkZipEntry_NextEntry(swigCPtr, this);
    return (cPtr == 0) ? null : new CkZipEntry(cPtr, true);
  }

  public boolean SaveLastError(String filename) {
    return chilkatJNI.CkZipEntry_SaveLastError(swigCPtr, this, filename);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkZipEntry_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkZipEntry_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkZipEntry_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

}
